{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 5,
  "build_id": "v0.99.1",
  "game_mode": "standard",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "STONE_HUMIDIFIER",
                "title": {
                  "key": "STONE_HUMIDIFIER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "POMANDER",
                "title": {
                  "key": "POMANDER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PRECARIOUS_SHEARS",
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_IRONCLAD"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_IRONCLAD"
              }
            ],
            "current_gold": 99,
            "current_hp": 51,
            "damage_taken": 13,
            "event_choices": [
              {
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 64,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.PRECARIOUS_SHEARS",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.RAMPAGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.RAMPAGE"
              }
            ],
            "current_gold": 108,
            "current_hp": 55,
            "damage_taken": 2,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_WEAK",
            "monster_ids": [
              "MONSTER.TWIG_SLIME_S",
              "MONSTER.TWIG_SLIME_M",
              "MONSTER.LEAF_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.BYRDONIS_EGG"
              }
            ],
            "current_gold": 108,
            "current_hp": 55,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BYRDONIS_NEST.pages.INITIAL.options.TAKE.title",
                  "table": "events"
                },
                "variables": {
                  "Card": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Byrdonis Egg"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.BYRDONIS_NEST",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ANGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.POMMEL_STRIKE"
              }
            ],
            "current_gold": 116,
            "current_hp": 60,
            "damage_taken": 1,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FUZZY_WURM_CRAWLER_WEAK",
            "monster_ids": [
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_IRONCLAD"
              }
            ],
            "current_gold": 116,
            "current_hp": 49,
            "damage_taken": 11,
            "event_choices": [
              {
                "title": {
                  "key": "DENSE_VEGETATION.pages.INITIAL.options.TRUDGE_ON.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.DENSE_VEGETATION",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.UPPERCUT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEMOKINESIS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.UPPERCUT"
              }
            ],
            "current_gold": 143,
            "current_hp": 34,
            "damage_taken": 21,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.EXPLOSIVE_AMPOULE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.TOXIC_EGG",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYRDONIS_ELITE",
            "monster_ids": [
              "MONSTER.BYRDONIS"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.BYRD_SWOOP"
                },
                "original_card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.BYRDONIS_EGG"
                }
              }
            ],
            "current_gold": 143,
            "current_hp": 34,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BYRDPIP",
                "was_picked": true
              }
            ],
            "rest_site_choices": [
              "HATCH"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 8,
                  "id": "CARD.ONE_TWO_PUNCH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.ONE_TWO_PUNCH"
              }
            ],
            "current_gold": 171,
            "current_hp": 7,
            "damage_taken": 33,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BRONZE_SCALES",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
            "monster_ids": [
              "MONSTER.BYGONE_EFFIGY"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 171,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 208,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 37,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.WHETSTONE",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.UPPERCUT",
              "CARD.STRIKE_IRONCLAD"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 11,
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GRAPPLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.SHRUG_IT_OFF"
              }
            ],
            "current_gold": 220,
            "current_hp": 35,
            "damage_taken": 2,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_WEAK",
            "monster_ids": [
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 12,
                  "id": "CARD.EVIL_EYE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HEADBUTT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GRAPPLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.EVIL_EYE"
              }
            ],
            "current_gold": 234,
            "current_hp": 34,
            "damage_taken": 7,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INKLETS_NORMAL",
            "monster_ids": [
              "MONSTER.INKLET",
              "MONSTER.INKLET",
              "MONSTER.INKLET"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 13,
                  "id": "CARD.TRUE_GRIT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.HAVOC"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.TRUE_GRIT"
              }
            ],
            "current_gold": 264,
            "current_hp": 37,
            "damage_taken": 3,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.ATTACK_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PRAYER_WHEEL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHROG_PARASITE_ELITE",
            "monster_ids": [
              "MONSTER.PHROG_PARASITE"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.STONE_ARMOR"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FIGHT_ME"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.TREMBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.RAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CINDER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.STONE_ARMOR"
              }
            ],
            "current_gold": 274,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.OVERGROWTH_CRAWLERS",
            "monster_ids": [
              "MONSTER.SHRINKER_BEETLE",
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 15,
                  "id": "CARD.BLOOD_WALL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ASHEN_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BODY_SLAM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.BLOOD_WALL"
              }
            ],
            "current_gold": 300,
            "current_hp": 33,
            "damage_taken": 16,
            "gold_gained": 26,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.LIQUID_BRONZE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.HAPPY_FLOWER",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYRDONIS_ELITE",
            "monster_ids": [
              "MONSTER.BYRDONIS"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 300,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 17,
                  "id": "CARD.STOKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PRIMAL_FORCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MANGLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.STOKE"
              }
            ],
            "current_gold": 375,
            "current_hp": 39,
            "damage_taken": 24,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CEREMONIAL_BEAST_BOSS",
            "monster_ids": [
              "MONSTER.CEREMONIAL_BEAST"
            ],
            "room_type": "boss",
            "turns_taken": 11
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "SILENT",
                "title": {
                  "key": "SEA_GLASS.SILENT.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "ALCHEMICAL_COFFER",
                "title": {
                  "key": "ALCHEMICAL_COFFER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "ARCHAIC_TOOTH",
                "title": {
                  "key": "ARCHAIC_TOOTH.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.ADRENALINE"
              },
              {
                "current_upgrade_level": 1,
                "id": "CARD.PREPARED"
              },
              {
                "id": "CARD.ECHOING_SLASH"
              },
              {
                "id": "CARD.PRECISE_CUT"
              }
            ],
            "current_gold": 375,
            "current_hp": 71,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SEA_GLASS.SILENT.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 32,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.SEA_GLASS",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.OROBAS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLOOD_WALL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.RAMPAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEMOKINESIS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.EVIL_EYE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BODY_SLAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CINDER"
                },
                "was_picked": false
              }
            ],
            "current_gold": 390,
            "current_hp": 77,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.ATTACK_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TUNNELER_WEAK",
            "monster_ids": [
              "MONSTER.TUNNELER"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 20,
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ANGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.STONE_ARMOR"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PILLAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ARMAMENTS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.SHRUG_IT_OFF"
              },
              {
                "id": "CARD.STONE_ARMOR"
              }
            ],
            "current_gold": 405,
            "current_hp": 80,
            "damage_taken": 2,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 5,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.ATTACK_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 1
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 21,
                  "id": "CARD.UNMOVABLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.STAMPEDE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ARMAMENTS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.JUGGLING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.UNMOVABLE"
              }
            ],
            "current_gold": 417,
            "current_hp": 80,
            "damage_taken": 6,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUMBERING_BEETLE_NORMAL",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_SILK",
              "MONSTER.SLUMBERING_BEETLE"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 22,
                  "id": "CARD.STAMPEDE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CINDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STONE_ARMOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 22,
                  "id": "CARD.DRUM_OF_BATTLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.STOMP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FIEND_FIRE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.STAMPEDE"
              },
              {
                "id": "CARD.DRUM_OF_BATTLE"
              }
            ],
            "current_gold": 426,
            "current_hp": 80,
            "damage_taken": 2,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_OBSCURA_NORMAL",
            "monster_ids": [
              "MONSTER.THE_OBSCURA"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 426,
            "current_hp": 80,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.UNMOVABLE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 24,
                  "id": "CARD.FEEL_NO_PAIN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PYRE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.TREMBLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.FEEL_NO_PAIN"
              }
            ],
            "current_gold": 455,
            "current_hp": 73,
            "damage_taken": 13,
            "gold_gained": 29,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.ATTACK_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.GORGET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 455,
            "current_hp": 73,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.STAMPEDE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 492,
            "current_hp": 73,
            "damage_taken": 0,
            "gold_gained": 37,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BREAKTHROUGH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.TREMBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ARMAMENTS"
                },
                "was_picked": false
              }
            ],
            "current_gold": 525,
            "current_hp": 73,
            "damage_taken": 6,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PERMAFROST",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.ENTOMANCER_ELITE",
            "monster_ids": [
              "MONSTER.ENTOMANCER"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 525,
            "current_hp": 73,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.RAMPAGE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLOOD_WALL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.STAMPEDE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.EVIL_EYE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.RAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": false
              }
            ],
            "current_gold": 532,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.BLOCK_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_NORMAL",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.BRIMSTONE"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GRAPPLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.COLOSSUS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INFERNO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SPLASH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ANOINTED"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_IRONCLAD"
              }
            ],
            "current_gold": 236,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 296,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.STABLE_SERUM",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BRIMSTONE",
                "was_picked": true
              },
              {
                "choice": "RELIC.CHANDELIER",
                "was_picked": false
              },
              {
                "choice": "RELIC.BOOK_OF_FIVE_RINGS",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.DEMON_FORM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ARMAMENTS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.STOKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DEMON_FORM"
              }
            ],
            "current_gold": 264,
            "current_hp": 73,
            "damage_taken": 12,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.REPTILE_TRINKET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
            ],
            "room_type": "elite",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 264,
            "current_hp": 73,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.STONE_ARMOR"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.MANGLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEMON_FORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRIMSON_MANTLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MANGLE"
              }
            ],
            "current_gold": 339,
            "current_hp": 47,
            "damage_taken": 32,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FORTIFIER",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.BLOCK_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KAISER_CRAB_BOSS",
            "monster_ids": [
              "MONSTER.CRUSHER",
              "MONSTER.ROCKET"
            ],
            "room_type": "boss",
            "turns_taken": 7
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "JEWELRY_BOX",
                "title": {
                  "key": "JEWELRY_BOX.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "LOOMING_FRUIT",
                "title": {
                  "key": "LOOMING_FRUIT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "FUR_COAT",
                "title": {
                  "key": "FUR_COAT.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 339,
            "current_hp": 73,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "FUR_COAT.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 26,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.FUR_COAT",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NONUPEIPE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ARMAMENTS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BREAKTHROUGH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DISMANTLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ARMAMENTS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.GRAPPLE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 347,
            "current_hp": 67,
            "damage_taken": 12,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TURRET_OPERATOR_WEAK",
            "monster_ids": [
              "MONSTER.LIVING_SHIELD",
              "MONSTER.TURRET_OPERATOR"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 36,
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.RAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.TRUE_GRIT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.RAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.BLOODLETTING"
              }
            ],
            "current_gold": 354,
            "current_hp": 73,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DEVOTED_SCULPTOR_WEAK",
            "monster_ids": [
              "MONSTER.DEVOTED_SCULPTOR"
            ],
            "room_type": "monster",
            "turns_taken": 1
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 37,
                  "id": "CARD.PACTS_END"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.TRUE_GRIT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CINDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.HAVOC"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PACTS_END"
              }
            ],
            "current_gold": 365,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BEETLE_JUICE",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.VULNERABLE_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_LOST_AND_FORGOTTEN_NORMAL",
            "monster_ids": [
              "MONSTER.THE_LOST",
              "MONSTER.THE_FORGOTTEN"
            ],
            "room_type": "monster",
            "turns_taken": 1
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 38,
                  "id": "CARD.VICIOUS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SPITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.TRUE_GRIT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MOLTEN_FIST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASHEN_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.VICIOUS"
              }
            ],
            "current_gold": 377,
            "current_hp": 80,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FROG_KNIGHT_NORMAL",
            "monster_ids": [
              "MONSTER.FROG_KNIGHT"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ONE_TWO_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GRAPPLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BRAND"
                },
                "was_picked": false
              }
            ],
            "current_gold": 407,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 5,
            "max_hp": 85,
            "max_hp_gained": 5,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FRUIT_JUICE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.FORTIFIER",
              "POTION.FRUIT_JUICE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.MERCURY_HOURGLASS",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MECHA_KNIGHT_ELITE",
            "monster_ids": [
              "MONSTER.MECHA_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 1
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 407,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.VICIOUS"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 442,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 35,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.FESTIVE_POPPER",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 42,
                  "id": "CARD.BLUDGEON"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.TREMBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STONE_ARMOR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BLUDGEON"
              }
            ],
            "current_gold": 474,
            "current_hp": 81,
            "damage_taken": 10,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.BEETLE_JUICE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.TINY_MAILBOX",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_NEXUS_ELITE",
            "monster_ids": [
              "MONSTER.SOUL_NEXUS"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.INFERNO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEADBUTT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.STAMPEDE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BODY_SLAM"
                },
                "was_picked": false
              }
            ],
            "current_gold": 489,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 4,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FABRICATOR_NORMAL",
            "monster_ids": [
              "MONSTER.FABRICATOR"
            ],
            "room_type": "monster",
            "turns_taken": 1
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.STOMP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.EVIL_EYE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 521,
            "current_hp": 85,
            "damage_taken": 5,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 5,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.SWIFT_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.SELF_FORMING_CLAY",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KNIGHTS_ELITE",
            "monster_ids": [
              "MONSTER.FLAIL_KNIGHT",
              "MONSTER.SPECTRAL_KNIGHT",
              "MONSTER.MAGI_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.STRIKE_DUMMY",
              "RELIC.BELT_BUCKLE"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.UPPERCUT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ARMAMENTS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CASCADE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STAMPEDE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.EQUILIBRIUM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.JACKPOT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 88,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 433,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FORTIFIER",
                "was_picked": false
              },
              {
                "choice": "POTION.DUPLICATOR",
                "was_picked": false
              },
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STRIKE_DUMMY",
                "was_picked": true
              },
              {
                "choice": "RELIC.BELT_BUCKLE",
                "was_picked": true
              },
              {
                "choice": "RELIC.PETRIFIED_TOAD",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 46,
                  "id": "CARD.FEEL_NO_PAIN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.JUGGLING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.RAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BREAKTHROUGH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DOMINATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FEED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.FEEL_NO_PAIN"
              }
            ],
            "current_gold": 96,
            "current_hp": 83,
            "damage_taken": 8,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.TOUCH_OF_INSANITY",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.AXEBOTS_NORMAL",
            "monster_ids": [
              "MONSTER.AXEBOT",
              "MONSTER.AXEBOT"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 96,
            "current_hp": 83,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.DEMON_FORM"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 96,
            "current_hp": 46,
            "damage_taken": 43,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.COLORLESS_POTION",
              "POTION.TOUCH_OF_INSANITY"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TEST_SUBJECT_BOSS",
            "monster_ids": [
              "MONSTER.TEST_SUBJECT"
            ],
            "room_type": "boss",
            "turns_taken": 9
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.IRONCLAD",
      "deck": [
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BASH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.RAMPAGE"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.POMMEL_STRIKE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 6,
          "id": "CARD.UPPERCUT"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.BYRD_SWOOP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 8,
          "id": "CARD.ONE_TWO_PUNCH"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 11,
          "id": "CARD.SHRUG_IT_OFF"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 12,
          "id": "CARD.EVIL_EYE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 13,
          "id": "CARD.TRUE_GRIT"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.STONE_ARMOR"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 15,
          "id": "CARD.BLOOD_WALL"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 17,
          "id": "CARD.STOKE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.ADRENALINE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 18,
          "id": "CARD.ECHOING_SLASH"
        },
        {
          "floor_added_to_deck": 18,
          "id": "CARD.PRECISE_CUT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 20,
          "id": "CARD.SHRUG_IT_OFF"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 20,
          "id": "CARD.STONE_ARMOR"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.UNMOVABLE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 22,
          "id": "CARD.STAMPEDE"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.DRUM_OF_BATTLE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 24,
          "id": "CARD.FEEL_NO_PAIN"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 31,
          "id": "CARD.DEMON_FORM"
        },
        {
          "floor_added_to_deck": 33,
          "id": "CARD.MANGLE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 36,
          "id": "CARD.BLOODLETTING"
        },
        {
          "floor_added_to_deck": 37,
          "id": "CARD.PACTS_END"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 38,
          "id": "CARD.VICIOUS"
        },
        {
          "floor_added_to_deck": 42,
          "id": "CARD.BLUDGEON"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 46,
          "id": "CARD.FEEL_NO_PAIN"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BURNING_BLOOD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.PRECARIOUS_SHEARS"
        },
        {
          "floor_added_to_deck": 6,
          "id": "RELIC.TOXIC_EGG"
        },
        {
          "floor_added_to_deck": 7,
          "id": "RELIC.BYRDPIP",
          "props": {
            "strings": [
              {
                "name": "Skin",
                "value": "version2"
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 8,
          "id": "RELIC.BRONZE_SCALES"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.WHETSTONE"
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.PRAYER_WHEEL"
        },
        {
          "floor_added_to_deck": 15,
          "id": "RELIC.HAPPY_FLOWER",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 0
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.SEA_GLASS",
          "props": {
            "model_ids": [
              {
                "name": "CharacterId",
                "value": "CHARACTER.SILENT"
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.GORGET"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.VAJRA"
        },
        {
          "floor_added_to_deck": 27,
          "id": "RELIC.PERMAFROST"
        },
        {
          "floor_added_to_deck": 30,
          "id": "RELIC.BRIMSTONE"
        },
        {
          "floor_added_to_deck": 31,
          "id": "RELIC.REPTILE_TRINKET"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.FUR_COAT",
          "props": {
            "bools": [
              {
                "name": "FurCoatCoordsSet",
                "value": true
              }
            ],
            "int_arrays": [
              {
                "name": "FurCoatCoordCols",
                "value": [
                  6,
                  5,
                  1,
                  4,
                  5,
                  4,
                  5
                ]
              },
              {
                "name": "FurCoatCoordRows",
                "value": [
                  5,
                  4,
                  4,
                  2,
                  3,
                  12,
                  9
                ]
              }
            ],
            "ints": [
              {
                "name": "FurCoatActIndex",
                "value": 2
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.MERCURY_HOURGLASS"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.FESTIVE_POPPER"
        },
        {
          "floor_added_to_deck": 42,
          "id": "RELIC.TINY_MAILBOX"
        },
        {
          "floor_added_to_deck": 44,
          "id": "RELIC.SELF_FORMING_CLAY"
        },
        {
          "floor_added_to_deck": 45,
          "id": "RELIC.STRIKE_DUMMY"
        },
        {
          "floor_added_to_deck": 45,
          "id": "RELIC.BELT_BUCKLE"
        }
      ]
    }
  ],
  "run_time": 2333,
  "schema_version": 8,
  "seed": "F069XB1EQ6",
  "start_time": 1775705486,
  "was_abandoned": false,
  "win": true
}