{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 5,
  "build_id": "v0.99.1",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.INFESTED_PRISMS_ELITE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "STONE_HUMIDIFIER",
                "title": {
                  "key": "STONE_HUMIDIFIER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "GOLDEN_PEARL",
                "title": {
                  "key": "GOLDEN_PEARL.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "LARGE_CAPSULE",
                "title": {
                  "key": "LARGE_CAPSULE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 249,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "GOLDEN_PEARL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 150,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.GOLDEN_PEARL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.SUBROUTINE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SUBROUTINE"
              }
            ],
            "current_gold": 259,
            "current_hp": 57,
            "damage_taken": 3,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_WEAK",
            "monster_ids": [
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.BULK_UP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCAVENGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BULK_UP"
              }
            ],
            "current_gold": 272,
            "current_hp": 41,
            "damage_taken": 16,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_WEAK",
            "monster_ids": [
              "MONSTER.TWIG_SLIME_S",
              "MONSTER.TWIG_SLIME_M",
              "MONSTER.LEAF_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.SPINNER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FERAL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HOLOGRAM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SPINNER"
              }
            ],
            "current_gold": 286,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SHRINKER_BEETLE_WEAK",
            "monster_ids": [
              "MONSTER.SHRINKER_BEETLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.ORRERY"
            ],
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BALL_LIGHTNING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.TURBO"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.HAILSTORM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.NULL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFRACT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.COMPACT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUNK_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BULK_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NULL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UPROAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAILSTORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DARK_SHACKLES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GOLD_AXE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CHARGE_BATTERY"
              },
              {
                "id": "CARD.TURBO"
              },
              {
                "id": "CARD.HAILSTORM"
              },
              {
                "id": "CARD.COMPACT"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_DEFECT"
              }
            ],
            "current_gold": 12,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 274,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.FRUIT_JUICE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ORRERY",
                "was_picked": true
              },
              {
                "choice": "RELIC.BOOK_OF_FIVE_RINGS",
                "was_picked": false
              },
              {
                "choice": "RELIC.PERMAFROST",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 12,
            "current_hp": 41,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WELLSPRING.pages.INITIAL.options.BOTTLE.title",
                  "table": "events"
                },
                "variables": {
                  "BatheCurses": {
                    "type": "BaseDynamic",
                    "decimal_value": 1,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ESSENCE_OF_DARKNESS",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.WELLSPRING",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.DARKNESS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TURBO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DARKNESS"
              }
            ],
            "current_gold": 42,
            "current_hp": 12,
            "damage_taken": 29,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.SPEED_POTION",
              "POTION.ESSENCE_OF_DARKNESS"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.SPARKLING_ROUGE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYRDONIS_ELITE",
            "monster_ids": [
              "MONSTER.BYRDONIS"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 42,
            "current_hp": 34,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 9,
                  "id": "CARD.GLACIER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SYNTHESIS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SMOKESTACK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GLACIER"
              }
            ],
            "current_gold": 74,
            "current_hp": 32,
            "damage_taken": 9,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 7,
            "max_hp": 82,
            "max_hp_gained": 7,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STRAWBERRY",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
            "monster_ids": [
              "MONSTER.BYGONE_EFFIGY"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 113,
            "current_hp": 32,
            "damage_taken": 0,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.TUNING_FORK",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 113,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 12,
                  "id": "CARD.HOTFIX"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SYNCHRONIZE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TESLA_COIL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HOTFIX"
              }
            ],
            "current_gold": 141,
            "current_hp": 43,
            "damage_taken": 13,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FOCUS_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.SKILL_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_MARBLES",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHROG_PARASITE_ELITE",
            "monster_ids": [
              "MONSTER.PHROG_PARASITE"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.LOOP"
              }
            ],
            "current_gold": 141,
            "current_hp": 43,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BRAIN_LEECH.pages.INITIAL.options.SHARE_KNOWLEDGE.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.BRAIN_LEECH",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.SUNDER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FERAL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TEMPEST"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SUNDER"
              }
            ],
            "current_gold": 168,
            "current_hp": 15,
            "damage_taken": 28,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
            "monster_ids": [
              "MONSTER.BYGONE_EFFIGY"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 15,
                  "id": "CARD.DOUBLE_ENERGY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUNK_UP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DOUBLE_ENERGY"
              }
            ],
            "current_gold": 176,
            "current_hp": 4,
            "damage_taken": 11,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLESSING_OF_THE_FORGE",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CUBEX_CONSTRUCT_NORMAL",
            "monster_ids": [
              "MONSTER.CUBEX_CONSTRUCT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 176,
            "current_hp": 28,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 17,
                  "id": "CARD.MACHINE_LEARNING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COOLANT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ALL_FOR_ONE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MACHINE_LEARNING"
              }
            ],
            "current_gold": 251,
            "current_hp": 9,
            "damage_taken": 19,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DUPLICATOR",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.FOCUS_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CEREMONIAL_BEAST_BOSS",
            "monster_ids": [
              "MONSTER.CEREMONIAL_BEAST"
            ],
            "room_type": "boss",
            "turns_taken": 9
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "NUTRITIOUS_SOUP",
                "title": {
                  "key": "NUTRITIOUS_SOUP.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "STORYBOOK",
                "title": {
                  "key": "STORYBOOK.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "TOY_BOX",
                "title": {
                  "key": "TOY_BOX.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.TEZCATARAS_EMBER"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_DEFECT"
                },
                "enchantment": "ENCHANTMENT.TEZCATARAS_EMBER"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.TEZCATARAS_EMBER"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_DEFECT"
                },
                "enchantment": "ENCHANTMENT.TEZCATARAS_EMBER"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.TEZCATARAS_EMBER"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_DEFECT"
                },
                "enchantment": "ENCHANTMENT.TEZCATARAS_EMBER"
              }
            ],
            "current_gold": 251,
            "current_hp": 67,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "NUTRITIOUS_SOUP.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 58,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.NUTRITIOUS_SOUP",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TEZCATARA",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.TURBO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              }
            ],
            "current_gold": 262,
            "current_hp": 58,
            "damage_taken": 9,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.SPEED_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TUNNELER_WEAK",
            "monster_ids": [
              "MONSTER.TUNNELER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.OVERCLOCK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.HOLOGRAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.HAILSTORM"
              },
              {
                "id": "CARD.OVERCLOCK"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.HAILSTORM"
              }
            ],
            "current_gold": 276,
            "current_hp": 32,
            "damage_taken": 26,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POTION_OF_BINDING",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.DEFRAGMENT"
              }
            ],
            "current_gold": 276,
            "current_hp": 32,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "INFESTED_AUTOMATON.pages.INITIAL.options.STUDY.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.INFESTED_AUTOMATON",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.PENDULUM"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TESLA_COIL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REBOOT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAILSTORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PANIC_BUTTON"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CALAMITY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LEAP"
              }
            ],
            "current_gold": 56,
            "current_hp": 32,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 220,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": false
              },
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PENDULUM",
                "was_picked": true
              },
              {
                "choice": "RELIC.STRIKE_DUMMY",
                "was_picked": false
              },
              {
                "choice": "RELIC.BREAD",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "current_gold": 56,
            "current_hp": 0,
            "damage_taken": 32,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.DUPLICATOR",
              "POTION.POTION_OF_BINDING"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM"
            ],
            "room_type": "elite",
            "turns_taken": 7
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.DEFECT",
      "deck": [
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.TEZCATARAS_EMBER"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.TEZCATARAS_EMBER"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.TEZCATARAS_EMBER"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ZAP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DUALCAST"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.SUBROUTINE"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.BULK_UP"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.SPINNER"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.CHARGE_BATTERY"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.COMPACT"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.DARKNESS"
        },
        {
          "floor_added_to_deck": 9,
          "id": "CARD.GLACIER"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.HOTFIX"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.LOOP"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.SUNDER"
        },
        {
          "floor_added_to_deck": 15,
          "id": "CARD.DOUBLE_ENERGY"
        },
        {
          "floor_added_to_deck": 17,
          "id": "CARD.MACHINE_LEARNING"
        },
        {
          "floor_added_to_deck": 20,
          "id": "CARD.HAILSTORM"
        },
        {
          "floor_added_to_deck": 20,
          "id": "CARD.OVERCLOCK"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.DEFRAGMENT"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.LEAP"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.CRACKED_CORE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.GOLDEN_PEARL"
        },
        {
          "floor_added_to_deck": 5,
          "id": "RELIC.ORRERY"
        },
        {
          "floor_added_to_deck": 7,
          "id": "RELIC.SPARKLING_ROUGE"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.STRAWBERRY"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.TUNING_FORK",
          "props": {
            "ints": [
              {
                "name": "SkillsPlayed",
                "value": 9
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 12,
          "id": "RELIC.BAG_OF_MARBLES"
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.VAJRA"
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.NUTRITIOUS_SOUP"
        },
        {
          "floor_added_to_deck": 22,
          "id": "RELIC.PENDULUM"
        }
      ]
    }
  ],
  "run_time": 1041,
  "schema_version": 8,
  "seed": "5GFWUTJR8D",
  "start_time": 1775708386,
  "was_abandoned": false,
  "win": false
}