{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 7,
  "build_id": "v0.105.1",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.KNOWLEDGE_DEMON_BOSS",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "PHIAL_HOLSTER",
                "title": {
                  "key": "PHIAL_HOLSTER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "BOOMING_CONCH",
                "title": {
                  "key": "BOOMING_CONCH.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PRECARIOUS_SHEARS",
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_DEFECT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_DEFECT"
              }
            ],
            "current_gold": 99,
            "current_hp": 44,
            "damage_taken": 16,
            "event_choices": [
              {
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.PRECARIOUS_SHEARS",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "LAVA_ROCK",
                "title": {
                  "key": "LAVA_ROCK.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "FISHING_ROD",
                "title": {
                  "key": "FISHING_ROD.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "CURSED_PEARL",
                "title": {
                  "key": "CURSED_PEARL.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GREED"
              }
            ],
            "current_gold": 432,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "CURSED_PEARL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 333,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.CURSED_PEARL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.FERAL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.OVERCLOCK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GO_FOR_THE_EYES"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FERAL"
              }
            ],
            "current_gold": 108,
            "current_hp": 30,
            "damage_taken": 14,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PROPHESIZE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PATTER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GATHER_LIGHT"
              }
            ],
            "current_gold": 444,
            "current_hp": 51,
            "damage_taken": 9,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_WEAK",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.NULL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUNK_UP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NULL"
              }
            ],
            "current_gold": 116,
            "current_hp": 24,
            "damage_taken": 6,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.RADIATE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHILD_OF_THE_STARS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.RADIATE"
              }
            ],
            "current_gold": 459,
            "current_hp": 46,
            "damage_taken": 5,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.MAZALETHS_GIFT",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.DISTRACTION"
              }
            ],
            "current_gold": 216,
            "current_hp": 24,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRASH_HEAP.pages.INITIAL.options.GRAB.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "cards_gained": [
              {
                "id": "CARD.HELLO_WORLD"
              }
            ],
            "current_gold": 559,
            "current_hp": 46,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRASH_HEAP.pages.INITIAL.options.GRAB.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TRASH_HEAP",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.CHILL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.GO_FOR_THE_EYES"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.CHILL"
              },
              {
                "floor_added_to_deck": 5,
                "id": "CARD.GO_FOR_THE_EYES"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_DEFECT"
              }
            ],
            "current_gold": 29,
            "current_hp": 24,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 87,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "bought_relics": [
              "RELIC.STONE_CRACKER",
              "RELIC.MINIATURE_CANNON"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SHINING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CONQUEROR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.JACK_OF_ALL_TRADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MAYHEM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HIDDEN_CACHE"
              },
              {
                "id": "CARD.PALE_BLUE_DOT"
              }
            ],
            "current_gold": 1,
            "current_hp": 46,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 558,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.STAR_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.KINGS_COURAGE",
                "was_picked": false
              },
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STONE_CRACKER",
                "was_picked": true
              },
              {
                "choice": "RELIC.MINIATURE_CANNON",
                "was_picked": true
              },
              {
                "choice": "RELIC.CAULDRON",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 6,
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.LIGHTNING_ROD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.CHARGE_BATTERY"
              }
            ],
            "current_gold": 29,
            "current_hp": 24,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_FUTURE_OF_POTIONS.pages.INITIAL.options.POTION.title",
                  "table": "events"
                },
                "variables": {
                  "Rarity": {
                    "type": "String",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Common"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_discarded": [
              "POTION.FLEX_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 6,
                  "id": "CARD.VOID_FORM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SEEKING_EDGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SWORD_SAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.VOID_FORM"
              }
            ],
            "current_gold": 1,
            "current_hp": 46,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_FUTURE_OF_POTIONS.pages.INITIAL.options.POTION.title",
                  "table": "events"
                },
                "variables": {
                  "Rarity": {
                    "type": "String",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Rare"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_discarded": [
              "POTION.MAZALETHS_GIFT"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THE_FUTURE_OF_POTIONS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "floor_added_to_deck": 6,
                  "id": "CARD.CHARGE_BATTERY"
                },
                "enchantment": "ENCHANTMENT.NIMBLE"
              }
            ],
            "current_gold": 29,
            "current_hp": 24,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SELF_HELP_BOOK.pages.INITIAL.options.READ_PASSAGE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.SHARP"
                  },
                  "floor_added_to_deck": 3,
                  "id": "CARD.RADIATE"
                },
                "enchantment": "ENCHANTMENT.SHARP"
              }
            ],
            "current_gold": 1,
            "current_hp": 46,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SELF_HELP_BOOK.pages.INITIAL.options.READ_THE_BACK.title",
                  "table": "events"
                },
                "variables": {
                  "Enchantment1": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Sharp"
                  },
                  "Enchantment2": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Nimble"
                  },
                  "Enchantment3": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Swift"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SELF_HELP_BOOK",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 29,
            "current_hp": 46,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 1,
            "current_hp": 46,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.VENERATE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 64,
            "current_hp": 46,
            "damage_taken": 0,
            "gold_gained": 35,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.GORGET",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 40,
            "current_hp": 46,
            "damage_taken": 0,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.PENDULUM",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SYNTHESIS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GO_FOR_THE_EYES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FTL"
                },
                "was_picked": false
              }
            ],
            "current_gold": 94,
            "current_hp": 32,
            "damage_taken": 14,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.BOOK_OF_FIVE_RINGS",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 10,
                  "id": "CARD.ALIGNMENT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GLIMMER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRUSH_UNDER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ALIGNMENT"
              }
            ],
            "current_gold": 72,
            "current_hp": 30,
            "damage_taken": 16,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.MUMMIFIED_HAND",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TERROR_EEL_ELITE",
            "monster_ids": [
              "MONSTER.TERROR_EEL"
            ],
            "room_type": "elite",
            "turns_taken": 9
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.TEMPEST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THUNDER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TEMPEST"
              }
            ],
            "current_gold": 103,
            "current_hp": 32,
            "damage_taken": 0,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.REFLECT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.REFLECT"
              }
            ],
            "current_gold": 83,
            "current_hp": 30,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUDGE_SPINNER_WEAK",
            "monster_ids": [
              "MONSTER.SLUDGE_SPINNER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 103,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 83,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.GUNK_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TEMPEST"
                },
                "was_picked": false
              }
            ],
            "current_gold": 116,
            "current_hp": 50,
            "damage_taken": 4,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.REFLECT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PARRY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.REFLECT"
              }
            ],
            "current_gold": 93,
            "current_hp": 51,
            "damage_taken": 1,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_NORMAL",
            "monster_ids": [
              "MONSTER.CALCIFIED_CULTIST",
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.VOLTAIC"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.WHITE_NOISE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TURBO"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.VOLTAIC"
              }
            ],
            "current_gold": 149,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.DATA_DISK",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.TYRANNY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SHINING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SUMMON_FORTH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TYRANNY"
              }
            ],
            "current_gold": 126,
            "current_hp": 43,
            "damage_taken": 8,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.REPTILE_TRINKET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SKULKING_COLONY_ELITE",
            "monster_ids": [
              "MONSTER.SKULKING_COLONY"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 149,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.VOLTAIC"
            ]
          },
          {
            "current_gold": 126,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.TYRANNY"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SPINNER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.VOLTAIC"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MULTI_CAST"
                },
                "was_picked": false
              }
            ],
            "current_gold": 224,
            "current_hp": 41,
            "damage_taken": 9,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_used": [
              "POTION.POWER_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.SEVEN_STARS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DYING_STAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRASH_LANDING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SEVEN_STARS"
              }
            ],
            "current_gold": 201,
            "current_hp": 20,
            "damage_taken": 23,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.LAGAVULIN_MATRIARCH_BOSS",
            "monster_ids": [
              "MONSTER.LAGAVULIN_MATRIARCH"
            ],
            "room_type": "boss",
            "turns_taken": 9
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "PAELS_HORN",
                "title": {
                  "key": "PAELS_HORN.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_TOOTH",
                "title": {
                  "key": "PAELS_TOOTH.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "PAELS_EYE",
                "title": {
                  "key": "PAELS_EYE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.CHILL"
              },
              {
                "floor_added_to_deck": 4,
                "id": "CARD.DISTRACTION"
              },
              {
                "floor_added_to_deck": 3,
                "id": "CARD.NULL"
              },
              {
                "floor_added_to_deck": 11,
                "id": "CARD.TEMPEST"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.ZAP"
              }
            ],
            "current_gold": 224,
            "current_hp": 68,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PAELS_TOOTH.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 27,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.PAELS_TOOTH",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "PAELS_TEARS",
                "title": {
                  "key": "PAELS_TEARS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_WING",
                "title": {
                  "key": "PAELS_WING.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "PAELS_EYE",
                "title": {
                  "key": "PAELS_EYE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 201,
            "current_hp": 64,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PAELS_WING.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 44,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.PAELS_WING",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.PAEL",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 18,
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.UPROAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 3,
                "id": "CARD.NULL"
              },
              {
                "current_upgrade_level": 1,
                "id": "CARD.COLD_SNAP"
              }
            ],
            "current_gold": 238,
            "current_hp": 58,
            "damage_taken": 10,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.SHIP_IN_A_BOTTLE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 216,
            "current_hp": 26,
            "damage_taken": 38,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.MAZALETHS_GIFT",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.SWIFT_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_EGG"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 138,
            "current_hp": 58,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WELCOME_TO_WONGOS.pages.INITIAL.options.BARGAIN_BIN.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.ANCHOR",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 116,
            "current_hp": 26,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WELCOME_TO_WONGOS.pages.INITIAL.options.BARGAIN_BIN.title",
                  "table": "events"
                },
                "variables": {
                  "BargainBinCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 100,
                    "bool_value": false,
                    "string_value": null
                  },
                  "MysteryBoxCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 300,
                    "bool_value": false,
                    "string_value": null
                  },
                  "FeaturedItemCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 200,
                    "bool_value": false,
                    "string_value": null
                  },
                  "MysteryBoxRelicCount": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "MysteryBoxCombatCount": {
                    "type": "BaseDynamic",
                    "decimal_value": 5,
                    "bool_value": false,
                    "string_value": null
                  },
                  "WongoPointAmount": {
                    "type": "BaseDynamic",
                    "decimal_value": 136,
                    "bool_value": false,
                    "string_value": null
                  },
                  "RemainingWongoPointAmount": {
                    "type": "BaseDynamic",
                    "decimal_value": 1864,
                    "bool_value": false,
                    "string_value": null
                  },
                  "TotalWongoBadgeAmount": {
                    "type": "BaseDynamic",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": null
                  },
                  "RandomRelic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Captain's Wheel"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.RED_MASK",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.WELCOME_TO_WONGOS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 138,
            "current_hp": 58,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "RANWID_THE_ELDER.pages.INITIAL.options.POTION.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_discarded": [
              "POTION.SHIP_IN_A_BOTTLE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_MARBLES",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 116,
            "current_hp": 26,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "RANWID_THE_ELDER.pages.INITIAL.options.POTION.title",
                  "table": "events"
                },
                "variables": {
                  "Potion": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Mazaleth's Gift"
                  },
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Miniature Cannon"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_discarded": [
              "POTION.MAZALETHS_GIFT"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BOWLER_HAT",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.RANWID_THE_ELDER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 21,
                  "id": "CARD.LIGHTNING_ROD"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 1,
                "id": "CARD.ZAP"
              },
              {
                "id": "CARD.LIGHTNING_ROD"
              }
            ],
            "cards_removed": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 18,
                "id": "CARD.NULL"
              }
            ],
            "current_gold": 138,
            "current_hp": 73,
            "damage_taken": 5,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.GIGANTIFICATION_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 21,
                  "id": "CARD.BEGONE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.BEGONE"
              }
            ],
            "cards_removed": [
              {
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.SHARP"
                },
                "floor_added_to_deck": 3,
                "id": "CARD.RADIATE"
              }
            ],
            "current_gold": 116,
            "current_hp": 14,
            "damage_taken": 12,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.DUPLICATOR",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 22,
                  "id": "CARD.BELIEVE_IN_YOU"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 22,
                "id": "CARD.BELIEVE_IN_YOU"
              }
            ],
            "current_gold": 7,
            "current_hp": 73,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 131,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "bought_colorless": [
              "CARD.PROLONG"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PROPHESIZE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TERRAFORMING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FURNACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAT_DOWN"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PROLONG"
              }
            ],
            "current_gold": 32,
            "current_hp": 14,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 84,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.STAR_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.KINGS_COURAGE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STRIKE_DUMMY",
                "was_picked": false
              },
              {
                "choice": "RELIC.HAPPY_FLOWER",
                "was_picked": false
              },
              {
                "choice": "RELIC.ROYAL_STAMP",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 23,
                  "id": "CARD.SHADOW_SHIELD"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 11,
                "id": "CARD.TEMPEST"
              },
              {
                "id": "CARD.SHADOW_SHIELD"
              }
            ],
            "current_gold": 38,
            "current_hp": 55,
            "damage_taken": 18,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_used": [
              "POTION.BLOCK_POTION",
              "POTION.GIGANTIFICATION_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.INTIMIDATING_HELMET",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CONQUEROR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFLECT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MONOLOGUE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 68,
            "current_hp": 5,
            "damage_taken": 9,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": true
              },
              {
                "choice": "RELIC.TUNGSTEN_ROD",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.ENTOMANCER_ELITE",
            "monster_ids": [
              "MONSTER.ENTOMANCER"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 77,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.CENTENNIAL_PUZZLE",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 110,
            "current_hp": 5,
            "damage_taken": 0,
            "gold_gained": 42,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.AMETHYST_AUBERGINE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.CLUMSY"
              }
            ],
            "current_gold": 77,
            "current_hp": 75,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.ORNATE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.STONE_CRACKER",
                "was_picked": true
              }
            ]
          },
          {
            "cards_gained": [
              {
                "id": "CARD.CLUMSY"
              }
            ],
            "current_gold": 110,
            "current_hp": 5,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.ORNATE.title",
                  "table": "events"
                },
                "variables": {
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clumsy"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.WAR_PAINT",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.PROLONG",
              "CARD.GATHER_LIGHT"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THIS_OR_THAT",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 26,
                  "id": "CARD.COOLANT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CHAOS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SCAVENGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 4,
                "id": "CARD.DISTRACTION"
              },
              {
                "id": "CARD.COOLANT"
              }
            ],
            "current_gold": 85,
            "current_hp": 68,
            "damage_taken": 7,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.MAZALETHS_GIFT",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 138,
            "current_hp": 1,
            "damage_taken": 5,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_used": [
              "POTION.COLORLESS_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.OVICOPTER_NORMAL",
            "monster_ids": [
              "MONSTER.OVICOPTER"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 85,
            "current_hp": 68,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "MEND"
            ]
          },
          {
            "current_gold": 138,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 44,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.UPROAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 5,
                "id": "CARD.CHILL"
              }
            ],
            "current_gold": 95,
            "current_hp": 51,
            "damage_taken": 17,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 28,
                  "id": "CARD.GUARDS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LARGESSE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GUARDS"
              }
            ],
            "current_gold": 169,
            "current_hp": 29,
            "damage_taken": 16,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_NORMAL",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 29,
                  "id": "CARD.HOLOGRAM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ADAPTIVE_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HOLOGRAM"
              }
            ],
            "current_gold": 125,
            "current_hp": 14,
            "damage_taken": 37,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.MAZALETHS_GIFT"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 227,
            "current_hp": 13,
            "damage_taken": 16,
            "gold_gained": 58,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.DISTILLED_CHAOS",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.DUPLICATOR"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": true
              },
              {
                "choice": "RELIC.SHURIKEN",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 125,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 227,
            "current_hp": 35,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 125,
            "current_hp": 0,
            "damage_taken": 36,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_used": [
              "POTION.EXPLOSIVE_AMPOULE"
            ]
          },
          {
            "current_gold": 227,
            "current_hp": 0,
            "damage_taken": 35,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_used": [
              "POTION.DISTILLED_CHAOS",
              "POTION.WEAK_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KNOWLEDGE_DEMON_BOSS",
            "monster_ids": [
              "MONSTER.KNOWLEDGE_DEMON"
            ],
            "room_type": "boss",
            "turns_taken": 12
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [
        {
          "id": "DAMAGE_LEADER",
          "rarity": "bronze"
        },
        {
          "id": "ELITE",
          "rarity": "bronze"
        },
        {
          "id": "HEALER",
          "rarity": "bronze"
        }
      ],
      "character": "CHARACTER.DEFECT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DUALCAST"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.FERAL"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.GO_FOR_THE_EYES"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 6,
          "id": "CARD.CHARGE_BATTERY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 14,
          "id": "CARD.VOLTAIC"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.COLD_SNAP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.ZAP"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.LIGHTNING_ROD"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.BELIEVE_IN_YOU"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 23,
          "id": "CARD.TEMPEST"
        },
        {
          "floor_added_to_deck": 23,
          "id": "CARD.SHADOW_SHIELD"
        },
        {
          "floor_added_to_deck": 25,
          "id": "CARD.CLUMSY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 26,
          "id": "CARD.DISTRACTION"
        },
        {
          "floor_added_to_deck": 26,
          "id": "CARD.COOLANT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 28,
          "id": "CARD.CHILL"
        },
        {
          "floor_added_to_deck": 29,
          "id": "CARD.HOLOGRAM"
        }
      ],
      "id": 76561198038467720,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.CRACKED_CORE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.PRECARIOUS_SHEARS"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.GORGET"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.BOOK_OF_FIVE_RINGS",
          "props": {
            "ints": [
              {
                "name": "CardsAdded",
                "value": 14
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.DATA_DISK"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.PAELS_TOOTH",
          "props": {
            "card_arrays": [
              {
                "name": "SerializableCards",
                "value": []
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 19,
          "id": "RELIC.ANCHOR"
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.BAG_OF_MARBLES"
        },
        {
          "floor_added_to_deck": 23,
          "id": "RELIC.INTIMIDATING_HELMET"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.CENTENNIAL_PUZZLE"
        },
        {
          "floor_added_to_deck": 25,
          "id": "RELIC.STONE_CRACKER"
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.VAJRA"
        }
      ]
    },
    {
      "badges": [
        {
          "id": "DEBUFFER",
          "rarity": "bronze"
        },
        {
          "id": "ELITE",
          "rarity": "bronze"
        }
      ],
      "character": "CHARACTER.REGENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FALLING_STAR"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.VENERATE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.GREED"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.GATHER_LIGHT"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.HELLO_WORLD"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.HIDDEN_CACHE"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.PALE_BLUE_DOT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 6,
          "id": "CARD.VOID_FORM"
        },
        {
          "floor_added_to_deck": 10,
          "id": "CARD.ALIGNMENT"
        },
        {
          "floor_added_to_deck": 11,
          "id": "CARD.REFLECT"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.REFLECT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 14,
          "id": "CARD.TYRANNY"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.SEVEN_STARS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.BEGONE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 22,
          "id": "CARD.PROLONG"
        },
        {
          "floor_added_to_deck": 25,
          "id": "CARD.CLUMSY"
        },
        {
          "floor_added_to_deck": 28,
          "id": "CARD.GUARDS"
        }
      ],
      "id": 76561198930034127,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.DIVINE_RIGHT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.CURSED_PEARL"
        },
        {
          "floor_added_to_deck": 5,
          "id": "RELIC.STONE_CRACKER"
        },
        {
          "floor_added_to_deck": 5,
          "id": "RELIC.MINIATURE_CANNON"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.PENDULUM",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 2
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.MUMMIFIED_HAND"
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.REPTILE_TRINKET"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.PAELS_WING",
          "props": {
            "ints": [
              {
                "name": "RewardsSacrificed",
                "value": 4
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 19,
          "id": "RELIC.RED_MASK"
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.BOWLER_HAT"
        },
        {
          "floor_added_to_deck": 23,
          "id": "RELIC.VAJRA"
        },
        {
          "floor_added_to_deck": 23,
          "id": "RELIC.TUNGSTEN_ROD"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.AMETHYST_AUBERGINE"
        },
        {
          "floor_added_to_deck": 25,
          "id": "RELIC.WAR_PAINT"
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.VENERABLE_TEA_SET",
          "props": {
            "bools": [
              {
                "name": "GainEnergyInNextCombat",
                "value": false
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.SHURIKEN"
        }
      ]
    }
  ],
  "run_time": 2044,
  "schema_version": 9,
  "seed": "GVN84LTW92",
  "start_time": 1778383479,
  "was_abandoned": false,
  "win": false
}