{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 10,
  "build_id": "v0.106.1",
  "game_mode": "standard",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "SCROLL_BOXES",
                "title": {
                  "key": "SCROLL_BOXES.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "NEOWS_TORMENT",
                "title": {
                  "key": "NEOWS_TORMENT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PRECARIOUS_SHEARS",
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.REFINE_BLADE"
              },
              {
                "id": "CARD.BEGONE"
              },
              {
                "id": "CARD.PILLAR_OF_CREATION"
              }
            ],
            "current_gold": 99,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SCROLL_BOXES.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.SCROLL_BOXES",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "ARCANE_SCROLL",
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "LEAD_PAPERWEIGHT",
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "LARGE_CAPSULE",
                "title": {
                  "key": "LARGE_CAPSULE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.KNIFE_TRAP"
              }
            ],
            "current_gold": 99,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.ARCANE_SCROLL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PATTER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HIDDEN_CACHE"
              }
            ],
            "current_gold": 108,
            "current_hp": 53,
            "damage_taken": 7,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PIERCING_WAIL"
              }
            ],
            "current_gold": 107,
            "current_hp": 53,
            "damage_taken": 3,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 108,
            "current_hp": 53,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "DROWNING_BEACON.pages.INITIAL.options.CLIMB.title",
                  "table": "events"
                },
                "variables": {
                  "Potion": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Glowwater Potion"
                  },
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Fresnel Lens"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 13,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.FRESNEL_LENS",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 107,
            "current_hp": 53,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "DROWNING_BEACON.pages.INITIAL.options.CLIMB.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 13,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.FRESNEL_LENS",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.DROWNING_BEACON",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 162,
            "current_hp": 53,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SUNKEN_TREASURY.pages.INITIAL.options.FIRST_CHEST.title",
                  "table": "events"
                },
                "variables": {
                  "SmallChestGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 54,
                    "bool_value": false,
                    "string_value": null
                  },
                  "LargeChestGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 319,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 54,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "current_gold": 172,
            "current_hp": 53,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SUNKEN_TREASURY.pages.INITIAL.options.FIRST_CHEST.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 65,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SUNKEN_TREASURY",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.RADIATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEGONE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 171,
            "current_hp": 50,
            "damage_taken": 3,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BLADE_DANCE"
              }
            ],
            "current_gold": 185,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUDGE_SPINNER_WEAK",
            "monster_ids": [
              "MONSTER.SLUDGE_SPINNER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.GAMMA_BLAST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GAMMA_BLAST"
              }
            ],
            "current_gold": 179,
            "current_hp": 45,
            "damage_taken": 5,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.REGEN_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "floor_added_to_deck": 6,
                  "id": "CARD.DASH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.NIMBLE"
                },
                "id": "CARD.DASH"
              }
            ],
            "current_gold": 195,
            "current_hp": 51,
            "damage_taken": 2,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_WEAK",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 179,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BEGONE"
            ]
          },
          {
            "current_gold": 195,
            "current_hp": 51,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.PIERCING_WAIL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "floor_added_to_deck": 8,
                  "id": "CARD.GLITTERSTREAM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "id": "CARD.PATTER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.NIMBLE"
                },
                "id": "CARD.GLITTERSTREAM"
              }
            ],
            "current_gold": 209,
            "current_hp": 43,
            "damage_taken": 17,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 15,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.COLORLESS_POTION",
              "POTION.REGEN_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ORICHALCUM",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.FLANKING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FLECHETTES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FLANKING"
              }
            ],
            "current_gold": 227,
            "current_hp": 39,
            "damage_taken": 12,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.GIGANTIFICATION_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.TINY_MAILBOX",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TERROR_EEL_ELITE",
            "monster_ids": [
              "MONSTER.TERROR_EEL"
            ],
            "room_type": "elite",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 243,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 34,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.STURDY_CLAMP",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 259,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.WAR_PAINT",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.DEFEND_SILENT",
              "CARD.DEFEND_SILENT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "floor_added_to_deck": 10,
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BLACK_HOLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.NIMBLE"
                },
                "id": "CARD.GATHER_LIGHT"
              }
            ],
            "current_gold": 269,
            "current_hp": 23,
            "damage_taken": 20,
            "gold_gained": 26,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.BLOCK_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.CENTENNIAL_PUZZLE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 10,
                  "id": "CARD.HIDDEN_DAGGERS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PINPOINT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CALCULATED_GAMBLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HIDDEN_DAGGERS"
              }
            ],
            "current_gold": 288,
            "current_hp": 21,
            "damage_taken": 18,
            "gold_gained": 29,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.GIGANTIFICATION_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.REGAL_PILLOW",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
            "monster_ids": [
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER"
            ],
            "room_type": "elite",
            "turns_taken": 9
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "bought_colorless": [
              "CARD.PROLONG"
            ],
            "bought_relics": [
              "RELIC.ANCHOR"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRUSH_UNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLIMMER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEGONE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHILD_OF_THE_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CALAMITY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PROLONG"
              }
            ],
            "current_gold": 29,
            "current_hp": 23,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 240,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.BLESSING_OF_THE_FORGE",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.KINGS_COURAGE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ANCHOR",
                "was_picked": true
              },
              {
                "choice": "RELIC.STRAWBERRY",
                "was_picked": false
              },
              {
                "choice": "RELIC.ORRERY",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.ACCURACY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.PREPARED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UP_MY_SLEEVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ACCURACY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DRAMATIC_ENTRANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ANOINTED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 11,
                "id": "CARD.ACCURACY"
              },
              {
                "floor_added_to_deck": 11,
                "id": "CARD.PREPARED"
              }
            ],
            "current_gold": 5,
            "current_hp": 21,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 283,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.SHIP_IN_A_BOTTLE",
                "was_picked": false
              },
              {
                "choice": "POTION.GAMBLERS_BREW",
                "was_picked": false
              },
              {
                "choice": "POTION.CURE_ALL",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.HAPPY_FLOWER",
                "was_picked": true
              },
              {
                "choice": "RELIC.HAPPY_FLOWER",
                "was_picked": false
              },
              {
                "choice": "RELIC.PEAR",
                "was_picked": false
              },
              {
                "choice": "RELIC.TOOLBOX",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "current_gold": 29,
            "current_hp": 23,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LEGENDS_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "cards_gained": [
              {
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "current_gold": 5,
            "current_hp": 21,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LEGENDS_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THE_LEGENDS_WERE_TRUE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.CONQUEROR"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CRUSH_UNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CONQUEROR"
              }
            ],
            "current_gold": 0,
            "current_hp": 22,
            "damage_taken": 1,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 29,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "floor_added_to_deck": 13,
                  "id": "CARD.ESCAPE_PLAN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.OUTBREAK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.NIMBLE"
                },
                "id": "CARD.ESCAPE_PLAN"
              }
            ],
            "current_gold": 0,
            "current_hp": 19,
            "damage_taken": 2,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 5,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.GREMLIN_MERC_NORMAL",
            "monster_ids": [
              "MONSTER.GREMLIN_MERC",
              "MONSTER.SNEAKY_GREMLIN",
              "MONSTER.FAT_GREMLIN"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 33,
            "current_hp": 22,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.MERCURY_HOURGLASS",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 37,
            "current_hp": 19,
            "damage_taken": 0,
            "gold_gained": 37,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.GAME_PIECE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 33,
            "current_hp": 40,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 37,
            "current_hp": 51,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 32,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              }
            ],
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.TYRANNY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.MONARCHS_GAZE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOREGONE_CONCLUSION"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TYRANNY"
              }
            ],
            "current_gold": 108,
            "current_hp": 31,
            "damage_taken": 9,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_used": [
              "POTION.SKILL_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.AFTERIMAGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.THE_HUNT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MURDER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.AFTERIMAGE"
              }
            ],
            "current_gold": 112,
            "current_hp": 20,
            "damage_taken": 31,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.SWIFT_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.WATERFALL_GIANT_BOSS",
            "monster_ids": [
              "MONSTER.WATERFALL_GIANT"
            ],
            "room_type": "boss",
            "turns_taken": 11
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "GLASS_EYE",
                "title": {
                  "key": "GLASS_EYE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "RADIANT_PEARL",
                "title": {
                  "key": "RADIANT_PEARL.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "ARCHAIC_TOOTH",
                "title": {
                  "key": "ARCHAIC_TOOTH.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 17,
                  "id": "CARD.METEOR_SHOWER"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.FALLING_STAR"
                }
              }
            ],
            "current_gold": 108,
            "current_hp": 55,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ARCHAIC_TOOTH.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.ARCHAIC_TOOTH",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "GLASS_EYE",
                "title": {
                  "key": "GLASS_EYE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "RADIANT_PEARL",
                "title": {
                  "key": "RADIANT_PEARL.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "TOUCH_OF_OROBAS",
                "title": {
                  "key": "TOUCH_OF_OROBAS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 112,
            "current_hp": 49,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "RADIANT_PEARL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 29,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.RADIANT_PEARL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.OROBAS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 122,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "floor_added_to_deck": 18,
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.NIMBLE"
                },
                "id": "CARD.DODGE_AND_ROLL"
              }
            ],
            "current_gold": 121,
            "current_hp": 44,
            "damage_taken": 5,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_EGG"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRUSH_UNDER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.PILLAR_OF_CREATION"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.PILLAR_OF_CREATION"
              }
            ],
            "current_gold": 133,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 19,
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PINPOINT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 8,
                "id": "CARD.FLANKING"
              },
              {
                "id": "CARD.FLICK_FLACK"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 8,
                "id": "CARD.FLANKING"
              }
            ],
            "current_gold": 130,
            "current_hp": 44,
            "damage_taken": 0,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.FIRE_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.CHARGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.KNOW_THY_PLACE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CHARGE"
              }
            ],
            "current_gold": 142,
            "current_hp": 42,
            "damage_taken": 13,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BLADE_DANCE"
              }
            ],
            "current_gold": 140,
            "current_hp": 31,
            "damage_taken": 13,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.HEART_OF_IRON"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.HUNTER_KILLER_NORMAL",
            "monster_ids": [
              "MONSTER.HUNTER_KILLER"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.BLACK_HOLE"
              }
            ],
            "current_gold": 142,
            "current_hp": 42,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "INFESTED_AUTOMATON.pages.INITIAL.options.STUDY.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "cards_gained": [
              {
                "id": "CARD.INFINITE_BLADES"
              }
            ],
            "current_gold": 140,
            "current_hp": 31,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "INFESTED_AUTOMATON.pages.INITIAL.options.STUDY.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.INFESTED_AUTOMATON",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 178,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.RIPPLE_BASIN",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 176,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "floor_added_to_deck": 23,
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.NIMBLE"
                },
                "id": "CARD.COSMIC_INDIFFERENCE"
              }
            ],
            "current_gold": 206,
            "current_hp": 5,
            "damage_taken": 37,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.POWDERED_DEMISE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.BLOCK_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PEN_NIB",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "floor_added_to_deck": 23,
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FINISHER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.NIMBLE"
                },
                "id": "CARD.DODGE_AND_ROLL"
              }
            ],
            "current_gold": 208,
            "current_hp": 6,
            "damage_taken": 25,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.SNECKO_OIL",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.ATTACK_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BOWLER_HAT",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM"
            ],
            "room_type": "elite",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 12,
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "completed_quests": [
              "CARD.SPOILS_MAP"
            ],
            "current_gold": 837,
            "current_hp": 5,
            "damage_taken": 0,
            "gold_gained": 631,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": true
              }
            ]
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 12,
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "completed_quests": [
              "CARD.SPOILS_MAP"
            ],
            "current_gold": 1004,
            "current_hp": 6,
            "damage_taken": 0,
            "gold_gained": 796,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.UNCEASING_TOP",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 837,
            "current_hp": 23,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 1004,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 32,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              }
            ],
            "potion_discarded": [
              "POTION.SNECKO_OIL"
            ],
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 894,
            "current_hp": 23,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LOST_WISP.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                },
                "variables": {
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Lost Wisp"
                  },
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Decay"
                  }
                }
              }
            ],
            "gold_gained": 57,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "cards_gained": [
              {
                "id": "CARD.DECAY"
              }
            ],
            "current_gold": 1004,
            "current_hp": 38,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LOST_WISP.pages.INITIAL.options.CLAIM.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.LOST_WISP",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.LOST_WISP",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 894,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 1004,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.AFTERIMAGE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "floor_added_to_deck": 28,
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.NIMBLE"
                },
                "id": "CARD.CLOAK_OF_STARS"
              }
            ],
            "current_gold": 921,
            "current_hp": 25,
            "damage_taken": 16,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POWDERED_DEMISE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STRIKE_DUMMY",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 28,
                  "id": "CARD.POUNCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BACKSTAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.POUNCE"
              }
            ],
            "current_gold": 1042,
            "current_hp": 31,
            "damage_taken": 7,
            "gold_gained": 38,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.CUNNING_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.BLOCK_POTION",
              "POTION.EXPLOSIVE_AMPOULE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.KUNAI",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": false
              }
            ],
            "current_gold": 928,
            "current_hp": 25,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 29,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PIERCING_WAIL"
              }
            ],
            "current_gold": 1054,
            "current_hp": 30,
            "damage_taken": 1,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_NORMAL",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 928,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 1054,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 27,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              }
            ],
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.BOMBARDMENT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.NEUTRON_AEGIS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DECISIONS_DECISIONS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BOMBARDMENT"
              }
            ],
            "current_gold": 1003,
            "current_hp": 40,
            "damage_taken": 3,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_used": [
              "POTION.POWER_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.SNEAKY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ECHOING_SLASH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THE_HUNT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SNEAKY"
              }
            ],
            "current_gold": 1147,
            "current_hp": 50,
            "damage_taken": 7,
            "gold_gained": 93,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_used": [
              "POTION.CUNNING_POTION",
              "POTION.COLORLESS_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KAISER_CRAB_BOSS",
            "monster_ids": [
              "MONSTER.CRUSHER",
              "MONSTER.ROCKET"
            ],
            "room_type": "boss",
            "turns_taken": 10
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "BLOOD_SOAKED_ROSE",
                "title": {
                  "key": "BLOOD_SOAKED_ROSE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PRESERVED_FOG",
                "title": {
                  "key": "PRESERVED_FOG.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "CHOICES_PARADOX",
                "title": {
                  "key": "CHOICES_PARADOX.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 1003,
            "current_hp": 57,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "CHOICES_PARADOX.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 17,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.CHOICES_PARADOX",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "WHISPERING_EARRING",
                "title": {
                  "key": "WHISPERING_EARRING.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "DISTINGUISHED_CAPE",
                "title": {
                  "key": "DISTINGUISHED_CAPE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "CHOICES_PARADOX",
                "title": {
                  "key": "CHOICES_PARADOX.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 1147,
            "current_hp": 55,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "CHOICES_PARADOX.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 5,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.CHOICES_PARADOX",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.VAKUU",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.KINGLY_PUNCH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CRUSH_UNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.KINGLY_PUNCH"
              }
            ],
            "current_gold": 1018,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "floor_added_to_deck": 33,
                  "id": "CARD.ESCAPE_PLAN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.NIMBLE"
                },
                "id": "CARD.ESCAPE_PLAN"
              }
            ],
            "current_gold": 1164,
            "current_hp": 49,
            "damage_taken": 6,
            "gold_gained": 17,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TURRET_OPERATOR_WEAK",
            "monster_ids": [
              "MONSTER.LIVING_SHIELD",
              "MONSTER.TURRET_OPERATOR"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 1018,
            "current_hp": 57,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "RELIC_TRADER.pages.INITIAL.options.MIDDLE.title",
                  "table": "events"
                },
                "variables": {
                  "TopRelicOwned": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Bag of Preparation"
                  },
                  "TopRelicNew": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Bronze Scales"
                  },
                  "MiddleRelicOwned": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Orichalcum"
                  },
                  "MiddleRelicNew": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Permafrost"
                  },
                  "BottomRelicOwned": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Pen Nib"
                  },
                  "BottomRelicNew": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Festive Popper"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.PERMAFROST",
                "was_picked": true
              }
            ],
            "relics_removed": [
              "RELIC.ORICHALCUM"
            ]
          },
          {
            "current_gold": 1164,
            "current_hp": 49,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "RELIC_TRADER.pages.INITIAL.options.TOP.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.INTIMIDATING_HELMET",
                "was_picked": true
              }
            ],
            "relics_removed": [
              "RELIC.BOWLER_HAT"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.RELIC_TRADER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_colorless": [
              "CARD.SHOCKWAVE"
            ],
            "bought_relics": [
              "RELIC.MINIATURE_TENT",
              "RELIC.STONE_CRACKER"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.GAMMA_BLAST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MAYHEM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SHOCKWAVE"
              },
              {
                "id": "CARD.STARDUST"
              },
              {
                "id": "CARD.CHILD_OF_THE_STARS"
              }
            ],
            "current_gold": 353,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 665,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.BLESSING_OF_THE_FORGE",
                "was_picked": false
              },
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": false
              },
              {
                "choice": "POTION.LUCKY_TONIC",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.MINIATURE_TENT",
                "was_picked": true
              },
              {
                "choice": "RELIC.STONE_CRACKER",
                "was_picked": true
              },
              {
                "choice": "RELIC.SPARKLING_ROUGE",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "id": "CARD.MIRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.OUTBREAK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DARK_SHACKLES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ALCHEMIZE"
                },
                "was_picked": false
              }
            ],
            "cards_enchanted": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.ROYALLY_APPROVED"
                  },
                  "floor_added_to_deck": 2,
                  "id": "CARD.PIERCING_WAIL"
                },
                "enchantment": "ENCHANTMENT.ROYALLY_APPROVED"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 26,
                "id": "CARD.DECAY"
              }
            ],
            "current_gold": 435,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 629,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PARRYING_SHIELD",
                "was_picked": true
              },
              {
                "choice": "RELIC.GORGET",
                "was_picked": true
              },
              {
                "choice": "RELIC.ROYAL_STAMP",
                "was_picked": true
              },
              {
                "choice": "RELIC.PARRYING_SHIELD",
                "was_picked": false
              },
              {
                "choice": "RELIC.GORGET",
                "was_picked": false
              },
              {
                "choice": "RELIC.ROYAL_STAMP",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 353,
            "current_hp": 57,
            "damage_taken": 0,
            "downgraded_cards": [
              "CARD.BEGONE"
            ],
            "event_choices": [
              {
                "title": {
                  "key": "REFLECTIONS.pages.INITIAL.options.TOUCH_A_MIRROR.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "upgraded_cards": [
              "CARD.HIDDEN_CACHE",
              "CARD.METEOR_SHOWER",
              "CARD.BEGONE",
              "CARD.DEFEND_REGENT"
            ]
          },
          {
            "cards_gained": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              },
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_SILENT"
              },
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.NEUTRALIZE"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.SURVIVOR"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.ASCENDERS_BANE"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.KNIFE_TRAP"
              },
              {
                "current_upgrade_level": 1,
                "enchantment": {
                  "amount": 1,
                  "id": "ENCHANTMENT.ROYALLY_APPROVED"
                },
                "floor_added_to_deck": 2,
                "id": "CARD.PIERCING_WAIL"
              },
              {
                "floor_added_to_deck": 5,
                "id": "CARD.BLADE_DANCE"
              },
              {
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.NIMBLE"
                },
                "floor_added_to_deck": 6,
                "id": "CARD.DASH"
              },
              {
                "floor_added_to_deck": 10,
                "id": "CARD.HIDDEN_DAGGERS"
              },
              {
                "floor_added_to_deck": 11,
                "id": "CARD.ACCURACY"
              },
              {
                "floor_added_to_deck": 11,
                "id": "CARD.PREPARED"
              },
              {
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.NIMBLE"
                },
                "floor_added_to_deck": 13,
                "id": "CARD.ESCAPE_PLAN"
              },
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 16,
                "id": "CARD.AFTERIMAGE"
              },
              {
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.NIMBLE"
                },
                "floor_added_to_deck": 18,
                "id": "CARD.DODGE_AND_ROLL"
              },
              {
                "floor_added_to_deck": 19,
                "id": "CARD.FLANKING"
              },
              {
                "floor_added_to_deck": 19,
                "id": "CARD.FLICK_FLACK"
              },
              {
                "floor_added_to_deck": 20,
                "id": "CARD.BLADE_DANCE"
              },
              {
                "floor_added_to_deck": 21,
                "id": "CARD.INFINITE_BLADES"
              },
              {
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.NIMBLE"
                },
                "floor_added_to_deck": 23,
                "id": "CARD.DODGE_AND_ROLL"
              },
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 28,
                "id": "CARD.POUNCE"
              },
              {
                "floor_added_to_deck": 29,
                "id": "CARD.PIERCING_WAIL"
              },
              {
                "floor_added_to_deck": 31,
                "id": "CARD.SNEAKY"
              },
              {
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.NIMBLE"
                },
                "floor_added_to_deck": 33,
                "id": "CARD.ESCAPE_PLAN"
              },
              {
                "id": "CARD.BAD_LUCK"
              }
            ],
            "current_gold": 435,
            "current_hp": 49,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "REFLECTIONS.pages.INITIAL.options.SHATTER.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.REFLECTIONS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "floor_added_to_deck": 37,
                  "id": "CARD.MANIFEST_AUTHORITY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SUMMON_FORTH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPOILS_OF_BATTLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.NIMBLE"
                },
                "id": "CARD.MANIFEST_AUTHORITY"
              }
            ],
            "current_gold": 362,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 449,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 395,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.GREMLIN_HORN",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 483,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 34,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.LETTER_OPENER",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.SOULS_POWER"
                  },
                  "floor_added_to_deck": 11,
                  "id": "CARD.PROLONG"
                },
                "enchantment": "ENCHANTMENT.SOULS_POWER"
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DECAY"
              }
            ],
            "current_gold": 395,
            "current_hp": 57,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "GRAVE_OF_THE_FORGOTTEN.pages.INITIAL.options.CONFRONT.title",
                  "table": "events"
                },
                "variables": {
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Forgotten Soul"
                  },
                  "Enchantment": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Soul's Power"
                  },
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Decay"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.SOULS_POWER"
                  },
                  "floor_added_to_deck": 29,
                  "id": "CARD.PIERCING_WAIL"
                },
                "enchantment": "ENCHANTMENT.SOULS_POWER"
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DECAY"
              }
            ],
            "current_gold": 483,
            "current_hp": 49,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "GRAVE_OF_THE_FORGOTTEN.pages.INITIAL.options.CONFRONT.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.GRAVE_OF_THE_FORGOTTEN",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.LANTERN"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SHINING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FURNACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DRAMATIC_ENTRANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAND_OF_GREED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ALIGNMENT"
              },
              {
                "id": "CARD.RESONANCE"
              }
            ],
            "current_gold": 52,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 343,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.DISTILLED_CHAOS",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.LANTERN",
                "was_picked": true
              },
              {
                "choice": "RELIC.WHETSTONE",
                "was_picked": false
              },
              {
                "choice": "RELIC.KIFUDA",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.MEMENTO_MORI"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STRATAGEM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MAYHEM"
                },
                "was_picked": false
              }
            ],
            "current_gold": 3,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 480,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.CLARITY",
                "was_picked": false
              },
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.JOSS_PAPER",
                "was_picked": true
              },
              {
                "choice": "RELIC.BAG_OF_MARBLES",
                "was_picked": true
              },
              {
                "choice": "RELIC.JOSS_PAPER",
                "was_picked": false
              },
              {
                "choice": "RELIC.BAG_OF_MARBLES",
                "was_picked": false
              },
              {
                "choice": "RELIC.NINJA_SCROLL",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 52,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.STARDUST"
            ]
          },
          {
            "current_gold": 3,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.PIERCING_WAIL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "floor_added_to_deck": 42,
                  "id": "CARD.PARTICLE_WALL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.RADIATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "enchantment": {
                  "amount": 2,
                  "id": "ENCHANTMENT.NIMBLE"
                },
                "id": "CARD.PARTICLE_WALL"
              }
            ],
            "current_gold": 66,
            "current_hp": 39,
            "damage_taken": 18,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SKEWER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              }
            ],
            "current_gold": 11,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_used": [
              "POTION.BLOCK_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.OWL_MAGISTRATE_NORMAL",
            "monster_ids": [
              "MONSTER.OWL_MAGISTRATE"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 99,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 50,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.RAINBOW_RING",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 99,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "HEAL",
              "MEND",
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BOMBARDMENT"
            ]
          },
          {
            "current_gold": 50,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 8,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.KNIFE_TRAP"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 99,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720
          },
          {
            "current_gold": 50,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.QUEEN_BOSS",
            "monster_ids": [
              "MONSTER.TORCH_HEAD_AMALGAM",
              "MONSTER.QUEEN"
            ],
            "room_type": "boss",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 99,
            "current_hp": 15,
            "damage_taken": 42,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_used": [
              "POTION.STRENGTH_POTION"
            ]
          },
          {
            "current_gold": 50,
            "current_hp": 21,
            "damage_taken": 36,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_used": [
              "POTION.ATTACK_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TEST_SUBJECT_BOSS",
            "monster_ids": [
              "MONSTER.TEST_SUBJECT"
            ],
            "room_type": "boss",
            "turns_taken": 10
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [
        {
          "id": "DEBUFFER",
          "rarity": "bronze"
        },
        {
          "id": "ELITE",
          "rarity": "bronze"
        },
        {
          "id": "HEALER",
          "rarity": "bronze"
        },
        {
          "id": "HIGHLANDER",
          "rarity": "bronze"
        },
        {
          "id": "KACHING",
          "rarity": "bronze"
        },
        {
          "id": "PERFECT",
          "rarity": "bronze"
        }
      ],
      "character": "CHARACTER.REGENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.VENERATE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.REFINE_BLADE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.BEGONE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.HIDDEN_CACHE"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.GAMMA_BLAST"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 8,
          "id": "CARD.GLITTERSTREAM"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 10,
          "id": "CARD.GATHER_LIGHT"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.SOULS_POWER"
          },
          "floor_added_to_deck": 11,
          "id": "CARD.PROLONG"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.CONQUEROR"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.TYRANNY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 17,
          "id": "CARD.METEOR_SHOWER"
        },
        {
          "floor_added_to_deck": 19,
          "id": "CARD.PILLAR_OF_CREATION"
        },
        {
          "floor_added_to_deck": 20,
          "id": "CARD.CHARGE"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.BLACK_HOLE"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 23,
          "id": "CARD.COSMIC_INDIFFERENCE"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 28,
          "id": "CARD.CLOAK_OF_STARS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 31,
          "id": "CARD.BOMBARDMENT"
        },
        {
          "floor_added_to_deck": 33,
          "id": "CARD.KINGLY_PUNCH"
        },
        {
          "floor_added_to_deck": 35,
          "id": "CARD.SHOCKWAVE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 35,
          "id": "CARD.STARDUST"
        },
        {
          "floor_added_to_deck": 35,
          "id": "CARD.CHILD_OF_THE_STARS"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 37,
          "id": "CARD.MANIFEST_AUTHORITY"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.DECAY"
        },
        {
          "floor_added_to_deck": 40,
          "id": "CARD.ALIGNMENT"
        },
        {
          "floor_added_to_deck": 40,
          "id": "CARD.RESONANCE"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 42,
          "id": "CARD.PARTICLE_WALL"
        }
      ],
      "id": 76561198038467720,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.DIVINE_RIGHT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.SCROLL_BOXES"
        },
        {
          "floor_added_to_deck": 3,
          "id": "RELIC.FRESNEL_LENS"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.STURDY_CLAMP"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.CENTENNIAL_PUZZLE"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.ANCHOR"
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.MERCURY_HOURGLASS"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.ARCHAIC_TOOTH",
          "props": {
            "cards": [
              {
                "name": "AncientCard",
                "value": {
                  "id": "CARD.METEOR_SHOWER"
                }
              },
              {
                "name": "StarterCard",
                "value": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.FALLING_STAR"
                }
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 22,
          "id": "RELIC.RIPPLE_BASIN"
        },
        {
          "floor_added_to_deck": 23,
          "id": "RELIC.PEN_NIB",
          "props": {
            "ints": [
              {
                "name": "AttacksPlayed",
                "value": 2
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.BAG_OF_PREPARATION"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.STRIKE_DUMMY"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.CHOICES_PARADOX"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.PERMAFROST"
        },
        {
          "floor_added_to_deck": 35,
          "id": "RELIC.MINIATURE_TENT"
        },
        {
          "floor_added_to_deck": 35,
          "id": "RELIC.STONE_CRACKER"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.GREMLIN_HORN"
        },
        {
          "floor_added_to_deck": 40,
          "id": "RELIC.LANTERN"
        },
        {
          "floor_added_to_deck": 43,
          "id": "RELIC.VENERABLE_TEA_SET",
          "props": {
            "bools": [
              {
                "name": "GainEnergyInNextCombat",
                "value": false
              }
            ]
          }
        }
      ]
    },
    {
      "badges": [
        {
          "id": "CCCCOMBO",
          "rarity": "bronze"
        },
        {
          "id": "DAMAGE_LEADER",
          "rarity": "bronze"
        },
        {
          "id": "ELITE",
          "rarity": "bronze"
        },
        {
          "id": "BIG_DECK",
          "rarity": "silver"
        },
        {
          "id": "PERFECT",
          "rarity": "bronze"
        },
        {
          "id": "TEAM_PLAYER",
          "rarity": "silver"
        }
      ],
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.NEUTRALIZE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SURVIVOR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.KNIFE_TRAP"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.ROYALLY_APPROVED"
          },
          "floor_added_to_deck": 2,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.BLADE_DANCE"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 6,
          "id": "CARD.DASH"
        },
        {
          "floor_added_to_deck": 10,
          "id": "CARD.HIDDEN_DAGGERS"
        },
        {
          "floor_added_to_deck": 11,
          "id": "CARD.ACCURACY"
        },
        {
          "floor_added_to_deck": 11,
          "id": "CARD.PREPARED"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 13,
          "id": "CARD.ESCAPE_PLAN"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 16,
          "id": "CARD.AFTERIMAGE"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 18,
          "id": "CARD.DODGE_AND_ROLL"
        },
        {
          "floor_added_to_deck": 19,
          "id": "CARD.FLANKING"
        },
        {
          "floor_added_to_deck": 19,
          "id": "CARD.FLICK_FLACK"
        },
        {
          "floor_added_to_deck": 20,
          "id": "CARD.BLADE_DANCE"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.INFINITE_BLADES"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 23,
          "id": "CARD.DODGE_AND_ROLL"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 28,
          "id": "CARD.POUNCE"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.SOULS_POWER"
          },
          "floor_added_to_deck": 29,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 31,
          "id": "CARD.SNEAKY"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 33,
          "id": "CARD.ESCAPE_PLAN"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 36,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 36,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 36,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 36,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 36,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.NEUTRALIZE"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 36,
          "id": "CARD.SURVIVOR"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.KNIFE_TRAP"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.ROYALLY_APPROVED"
          },
          "floor_added_to_deck": 36,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.BLADE_DANCE"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 36,
          "id": "CARD.DASH"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.HIDDEN_DAGGERS"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.ACCURACY"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.PREPARED"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 36,
          "id": "CARD.ESCAPE_PLAN"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 36,
          "id": "CARD.AFTERIMAGE"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 36,
          "id": "CARD.DODGE_AND_ROLL"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.FLANKING"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.FLICK_FLACK"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.BLADE_DANCE"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.INFINITE_BLADES"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 36,
          "id": "CARD.DODGE_AND_ROLL"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 36,
          "id": "CARD.POUNCE"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.SNEAKY"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 36,
          "id": "CARD.ESCAPE_PLAN"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.BAD_LUCK"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.DECAY"
        }
      ],
      "id": 76561198930034127,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.ARCANE_SCROLL"
        },
        {
          "floor_added_to_deck": 3,
          "id": "RELIC.FRESNEL_LENS"
        },
        {
          "floor_added_to_deck": 8,
          "id": "RELIC.TINY_MAILBOX"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.WAR_PAINT"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.REGAL_PILLOW"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.HAPPY_FLOWER",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 1
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.GAME_PIECE"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.RADIANT_PEARL"
        },
        {
          "floor_added_to_deck": 22,
          "id": "RELIC.VAJRA"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.UNCEASING_TOP"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.LOST_WISP"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.KUNAI"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.CHOICES_PARADOX"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.INTIMIDATING_HELMET"
        },
        {
          "floor_added_to_deck": 35,
          "id": "RELIC.PARRYING_SHIELD"
        },
        {
          "floor_added_to_deck": 35,
          "id": "RELIC.GORGET"
        },
        {
          "floor_added_to_deck": 35,
          "id": "RELIC.ROYAL_STAMP"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.LETTER_OPENER"
        },
        {
          "floor_added_to_deck": 40,
          "id": "RELIC.JOSS_PAPER",
          "props": {
            "ints": [
              {
                "name": "CardsExhausted",
                "value": 3
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 40,
          "id": "RELIC.BAG_OF_MARBLES"
        },
        {
          "floor_added_to_deck": 43,
          "id": "RELIC.RAINBOW_RING"
        }
      ]
    }
  ],
  "run_time": 3718,
  "schema_version": 9,
  "seed": "7VP6GLZSVU",
  "start_time": 1780257941,
  "was_abandoned": false,
  "win": true
}