{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 10,
  "build_id": "v0.108.0",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.RUBY_RAIDERS_NORMAL",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "LOST_COFFER",
                "title": {
                  "key": "LOST_COFFER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "ARCANE_SCROLL",
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "SILKEN_TRESS",
                "title": {
                  "key": "SILKEN_TRESS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.REBOOT"
              }
            ],
            "current_gold": 99,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.ARCANE_SCROLL",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "ancient_choice": [
              {
                "TextKey": "KALEIDOSCOPE",
                "title": {
                  "key": "KALEIDOSCOPE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "LAVA_ROCK",
                "title": {
                  "key": "LAVA_ROCK.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "LEAFY_POULTICE",
                "title": {
                  "key": "LEAFY_POULTICE.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.PRIMAL_FORCE"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_IRONCLAD"
                }
              },
              {
                "final_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.INFERNAL_BLADE"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.DEFEND_IRONCLAD"
                }
              }
            ],
            "current_gold": 99,
            "current_hp": 64,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LEAFY_POULTICE.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 64,
            "is_affected_by_fur_coat": false,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 12,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.LEAFY_POULTICE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.CHAOS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SKIM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LIGHTNING_ROD"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CHAOS"
              }
            ],
            "current_gold": 110,
            "current_hp": 50,
            "damage_taken": 10,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAVOC"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 112,
            "current_hp": 65,
            "damage_taken": 5,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_WEAK",
            "monster_ids": [
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "current_gold": 110,
            "current_hp": 50,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LEGENDS_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "stolen_loot": 0
          },
          {
            "cards_gained": [
              {
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "current_gold": 112,
            "current_hp": 65,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LEGENDS_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THE_LEGENDS_WERE_TRUE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TURBO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COMPACT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SMOKESTACK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.VOLLEY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ETERNAL_ARMOR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NULL"
              }
            ],
            "current_gold": 72,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 38,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.BLESSING_OF_THE_FORGE",
                "was_picked": false
              },
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              },
              {
                "choice": "POTION.GAMBLERS_BREW",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PENDULUM",
                "was_picked": false
              },
              {
                "choice": "RELIC.REGAL_PILLOW",
                "was_picked": false
              },
              {
                "choice": "RELIC.CHEMICAL_X",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.TREMBLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.HEADBUTT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HEADBUTT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASHEN_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TREMBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TAUNT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FEEL_NO_PAIN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPLASH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SECRET_WEAPON"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 4,
                "id": "CARD.TREMBLE"
              },
              {
                "floor_added_to_deck": 4,
                "id": "CARD.HEADBUTT"
              }
            ],
            "current_gold": 10,
            "current_hp": 65,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 102,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STRIKE_DUMMY",
                "was_picked": false
              },
              {
                "choice": "RELIC.BOOK_OF_FIVE_RINGS",
                "was_picked": false
              },
              {
                "choice": "RELIC.GNARLED_HAMMER",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TURBO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DOUBLE_ENERGY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.COOLHEADED"
              }
            ],
            "current_gold": 81,
            "current_hp": 46,
            "damage_taken": 4,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.RUPTURE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FORGOTTEN_RITUAL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ARMAMENTS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.RUPTURE"
              }
            ],
            "current_gold": 20,
            "current_hp": 65,
            "damage_taken": 6,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FUZZY_WURM_CRAWLER_WEAK",
            "monster_ids": [
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SWEEPING_BEAM"
              }
            ],
            "current_gold": 94,
            "current_hp": 42,
            "damage_taken": 4,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.RADIANT_TINCTURE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CINDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BREAKTHROUGH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SHRUG_IT_OFF"
              }
            ],
            "current_gold": 28,
            "current_hp": 58,
            "damage_taken": 13,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_WEAK",
            "monster_ids": [
              "MONSTER.LEAF_SLIME_S",
              "MONSTER.TWIG_SLIME_M",
              "MONSTER.TWIG_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.SHADOW_SHIELD"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SCAVENGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOOT_SEQUENCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SHADOW_SHIELD"
              }
            ],
            "current_gold": 124,
            "current_hp": 19,
            "damage_taken": 23,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.WAR_PAINT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.DEFEND_DEFECT",
              "CARD.DEFEND_DEFECT"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RUPTURE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ONE_TWO_PUNCH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BLOODLETTING"
              }
            ],
            "current_gold": 56,
            "current_hp": 41,
            "damage_taken": 23,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "potion_used": [
              "POTION.DEXTERITY_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.CENTENNIAL_PUZZLE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHROG_PARASITE_ELITE",
            "monster_ids": [
              "MONSTER.PHROG_PARASITE",
              "MONSTER.WRIGGLER"
            ],
            "room_type": "elite",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 124,
            "current_hp": 0,
            "damage_taken": 19,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198930034127,
            "stolen_loot": 0
          },
          {
            "current_gold": 56,
            "current_hp": 0,
            "damage_taken": 41,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198038467720,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.RUBY_RAIDERS_NORMAL",
            "monster_ids": [
              "MONSTER.ASSASSIN_RUBY_RAIDER",
              "MONSTER.CROSSBOW_RUBY_RAIDER",
              "MONSTER.BRUTE_RUBY_RAIDER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [],
      "character": "CHARACTER.DEFECT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ZAP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DUALCAST"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.REBOOT"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.CHAOS"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.SPOILS_MAP",
          "props": {
            "ints": [
              {
                "name": "SpoilsActIndex",
                "value": 1
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.NULL"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.COOLHEADED"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.SWEEPING_BEAM"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.SHADOW_SHIELD"
        }
      ],
      "id": 76561198930034127,
      "max_potion_slot_count": 2,
      "potions": [
        {
          "id": "POTION.HEART_OF_IRON",
          "slot_index": 0
        },
        {
          "id": "POTION.RADIANT_TINCTURE",
          "slot_index": 1
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.CRACKED_CORE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.ARCANE_SCROLL"
        },
        {
          "floor_added_to_deck": 7,
          "id": "RELIC.WAR_PAINT"
        }
      ]
    },
    {
      "badges": [
        {
          "id": "DAMAGE_LEADER",
          "rarity": "bronze"
        },
        {
          "id": "DEBUFFER",
          "rarity": "bronze"
        }
      ],
      "character": "CHARACTER.IRONCLAD",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BASH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PRIMAL_FORCE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.INFERNAL_BLADE"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.SPOILS_MAP",
          "props": {
            "ints": [
              {
                "name": "SpoilsActIndex",
                "value": 1
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.TREMBLE"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.HEADBUTT"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.RUPTURE"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.SHRUG_IT_OFF"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.BLOODLETTING"
        }
      ],
      "id": 76561198038467720,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BURNING_BLOOD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.LEAFY_POULTICE"
        },
        {
          "floor_added_to_deck": 7,
          "id": "RELIC.CENTENNIAL_PUZZLE"
        }
      ]
    }
  ],
  "run_time": 509,
  "schema_version": 9,
  "seed": "AYKU2W8XE1",
  "start_time": 1783661968,
  "was_abandoned": false,
  "win": false
}