{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 1,
  "build_id": "v0.108.0",
  "game_mode": "daily",
  "killed_by_encounter": "ENCOUNTER.KNOWLEDGE_DEMON_BOSS",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.PILLAGE"
              },
              {
                "id": "CARD.THRASH"
              },
              {
                "id": "CARD.DISMANTLE"
              },
              {
                "id": "CARD.ONE_TWO_PUNCH"
              },
              {
                "id": "CARD.FEEL_NO_PAIN"
              },
              {
                "id": "CARD.NOT_YET"
              },
              {
                "id": "CARD.BRAND"
              },
              {
                "id": "CARD.DEMON_FORM"
              },
              {
                "id": "CARD.SECOND_WIND"
              },
              {
                "id": "CARD.DRUM_OF_BATTLE"
              },
              {
                "id": "CARD.DARK_EMBRACE"
              },
              {
                "id": "CARD.HOWL_FROM_BEYOND"
              },
              {
                "id": "CARD.BRAND"
              },
              {
                "id": "CARD.HEMOKINESIS"
              },
              {
                "id": "CARD.PERFECTED_STRIKE"
              },
              {
                "id": "CARD.HOWL_FROM_BEYOND"
              },
              {
                "id": "CARD.FLAME_BARRIER"
              },
              {
                "id": "CARD.IMPERVIOUS"
              },
              {
                "id": "CARD.STOMP"
              },
              {
                "id": "CARD.CRIMSON_MANTLE"
              },
              {
                "id": "CARD.OFFERING"
              },
              {
                "id": "CARD.STONE_ARMOR"
              },
              {
                "id": "CARD.INFLAME"
              },
              {
                "id": "CARD.DISMANTLE"
              },
              {
                "id": "CARD.FORGOTTEN_RITUAL"
              },
              {
                "id": "CARD.NOT_YET"
              },
              {
                "id": "CARD.BODY_SLAM"
              },
              {
                "id": "CARD.BLOOD_WALL"
              },
              {
                "id": "CARD.NOT_YET"
              },
              {
                "id": "CARD.RAMPAGE"
              }
            ],
            "current_gold": 99,
            "current_hp": 79,
            "damage_taken": 1,
            "event_choices": [
              {
                "title": {
                  "key": "INSANITY.title",
                  "table": "modifiers"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 80,
            "is_affected_by_fur_coat": false,
            "max_hp": 79,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "stolen_loot": 0
          },
          {
            "cards_gained": [
              {
                "id": "CARD.REBOOT"
              },
              {
                "id": "CARD.ALL_FOR_ONE"
              },
              {
                "id": "CARD.GO_FOR_THE_EYES"
              },
              {
                "id": "CARD.REBOOT"
              },
              {
                "id": "CARD.COMPACT"
              },
              {
                "id": "CARD.FLAK_CANNON"
              },
              {
                "id": "CARD.ITERATION"
              },
              {
                "id": "CARD.REBOOT"
              },
              {
                "id": "CARD.CLAW"
              },
              {
                "id": "CARD.GENETIC_ALGORITHM",
                "props": {
                  "ints": [
                    {
                      "name": "CurrentBlock",
                      "value": 1
                    },
                    {
                      "name": "IncreasedBlock",
                      "value": 0
                    }
                  ]
                }
              },
              {
                "id": "CARD.STORM"
              },
              {
                "id": "CARD.RAINBOW"
              },
              {
                "id": "CARD.SPINNER"
              },
              {
                "id": "CARD.HELIX_DRILL"
              },
              {
                "id": "CARD.CONSUMING_SHADOW"
              },
              {
                "id": "CARD.SUNDER"
              },
              {
                "id": "CARD.FOCUSED_STRIKE"
              },
              {
                "id": "CARD.VOLTAIC"
              },
              {
                "id": "CARD.TRASH_TO_TREASURE"
              },
              {
                "id": "CARD.VOLTAIC"
              },
              {
                "id": "CARD.OVERCLOCK"
              },
              {
                "id": "CARD.VOLTAIC"
              },
              {
                "id": "CARD.OVERCLOCK"
              },
              {
                "id": "CARD.LEAP"
              },
              {
                "id": "CARD.GO_FOR_THE_EYES"
              },
              {
                "id": "CARD.MACHINE_LEARNING"
              },
              {
                "id": "CARD.ADAPTIVE_STRIKE"
              },
              {
                "id": "CARD.FOCUSED_STRIKE"
              },
              {
                "id": "CARD.ICE_LANCE"
              },
              {
                "id": "CARD.CHILL"
              }
            ],
            "current_gold": 99,
            "current_hp": 74,
            "damage_taken": 1,
            "event_choices": [
              {
                "title": {
                  "key": "INSANITY.title",
                  "table": "modifiers"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 75,
            "is_affected_by_fur_coat": false,
            "max_hp": 74,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.HAVOC"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CONQUEROR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRUSH_UNDER"
                },
                "was_picked": false
              }
            ],
            "current_gold": 117,
            "current_hp": 78,
            "damage_taken": 8,
            "gold_gained": 18,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 7,
            "is_affected_by_fur_coat": false,
            "max_hp": 78,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.BLACK_HOLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.STARDUST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GO_FOR_THE_EYES"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BLACK_HOLE"
              }
            ],
            "current_gold": 118,
            "current_hp": 72,
            "damage_taken": 2,
            "gold_gained": 19,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 73,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.RADIANT_TINCTURE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SHRINKER_BEETLE_WEAK",
            "monster_ids": [
              "MONSTER.SHRINKER_BEETLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PATTER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CINDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 133,
            "current_hp": 77,
            "damage_taken": 1,
            "gold_gained": 16,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 77,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.FUSION"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRUSH_UNDER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FUSION"
              }
            ],
            "current_gold": 133,
            "current_hp": 72,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 72,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_WEAK",
            "monster_ids": [
              "MONSTER.TWIG_SLIME_S",
              "MONSTER.LEAF_SLIME_M",
              "MONSTER.LEAF_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.SOWN"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.DEMON_FORM"
                },
                "enchantment": "ENCHANTMENT.SOWN"
              }
            ],
            "current_gold": 133,
            "current_hp": 76,
            "damage_taken": 1,
            "event_choices": [
              {
                "title": {
                  "key": "SAPPHIRE_SEED.pages.INITIAL.options.PLANT.title",
                  "table": "events"
                },
                "variables": {
                  "Enchantment": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Sown"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "stolen_loot": 0
          },
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.SOWN"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.GENETIC_ALGORITHM",
                  "props": {
                    "ints": [
                      {
                        "name": "CurrentBlock",
                        "value": 7
                      },
                      {
                        "name": "IncreasedBlock",
                        "value": 6
                      }
                    ]
                  }
                },
                "enchantment": "ENCHANTMENT.SOWN"
              }
            ],
            "current_gold": 133,
            "current_hp": 71,
            "damage_taken": 1,
            "event_choices": [
              {
                "title": {
                  "key": "SAPPHIRE_SEED.pages.INITIAL.options.PLANT.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 71,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SAPPHIRE_SEED",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 133,
            "current_hp": 61,
            "damage_taken": 15,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.CHOSEN_CHEESE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 133,
            "current_hp": 56,
            "damage_taken": 15,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.CHOSEN_CHEESE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ROOM_FULL_OF_CHEESE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.HOWL_FROM_BEYOND"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.I_AM_INVINCIBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INFERNO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPLASH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_GEM"
                },
                "was_picked": false
              }
            ],
            "current_gold": 34,
            "current_hp": 61,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 99,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 74,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.CLARITY",
                "was_picked": false
              },
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.CENTENNIAL_PUZZLE",
                "was_picked": false
              },
              {
                "choice": "RELIC.RIPPLE_BASIN",
                "was_picked": false
              },
              {
                "choice": "RELIC.BURNING_STICKS",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          },
          {
            "bought_potions": [
              "POTION.DUPLICATOR"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEVASTATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MODDED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PALE_BLUE_DOT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.JACK_OF_ALL_TRADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOSTALGIA"
                },
                "was_picked": false
              }
            ],
            "current_gold": 59,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 74,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 69,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.DUPLICATOR",
                "was_picked": true
              },
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              },
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.CANDELABRA",
                "was_picked": false
              },
              {
                "choice": "RELIC.ODDLY_SMOOTH_STONE",
                "was_picked": false
              },
              {
                "choice": "RELIC.BELT_BUCKLE",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 34,
            "current_hp": 73,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TABLET_OF_TRUTH.pages.INITIAL.options.SMASH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 12,
            "is_affected_by_fur_coat": false,
            "max_hp": 73,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "stolen_loot": 0
          },
          {
            "current_gold": 59,
            "current_hp": 68,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TABLET_OF_TRUTH.pages.INITIAL.options.SMASH.title",
                  "table": "events"
                },
                "variables": {
                  "SmashHPGain": {
                    "type": "BaseDynamic",
                    "decimal_value": 20,
                    "bool_value": false,
                    "string_value": null
                  },
                  "DecipherMaxHpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 12,
            "is_affected_by_fur_coat": false,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TABLET_OF_TRUTH",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 34,
            "current_hp": 72,
            "damage_taken": 1,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 72,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.DEMON_FORM"
            ]
          },
          {
            "current_gold": 59,
            "current_hp": 67,
            "damage_taken": 1,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 67,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.OVERCLOCK"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 82,
            "current_hp": 78,
            "damage_taken": 1,
            "gold_gained": 48,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 7,
            "is_affected_by_fur_coat": false,
            "max_hp": 78,
            "max_hp_gained": 7,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.STRAWBERRY",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 104,
            "current_hp": 66,
            "damage_taken": 1,
            "gold_gained": 45,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.RAZOR_TOOTH",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 82,
            "current_hp": 77,
            "damage_taken": 1,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 77,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.CRIMSON_MANTLE"
            ]
          },
          {
            "current_gold": 104,
            "current_hp": 65,
            "damage_taken": 1,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.GENETIC_ALGORITHM"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.EXPECT_A_FIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BODY_SLAM"
                },
                "was_picked": false
              }
            ],
            "current_gold": 122,
            "current_hp": 77,
            "damage_taken": 27,
            "gold_gained": 40,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 27,
            "is_affected_by_fur_coat": false,
            "max_hp": 77,
            "max_hp_gained": 1,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BLOOD_VIAL",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.GLOW"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ORBIT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GLOW"
              }
            ],
            "current_gold": 143,
            "current_hp": 53,
            "damage_taken": 13,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "is_affected_by_fur_coat": false,
            "max_hp": 65,
            "max_hp_gained": 1,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.JUZU_BRACELET",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYRDONIS_ELITE",
            "monster_ids": [
              "MONSTER.BYRDONIS"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 12,
                  "id": "CARD.UPPERCUT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GAMMA_BLAST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.UPPERCUT"
              }
            ],
            "current_gold": 140,
            "current_hp": 77,
            "damage_taken": 4,
            "gold_gained": 18,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 4,
            "is_affected_by_fur_coat": false,
            "max_hp": 77,
            "max_hp_gained": 1,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COMPACT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 156,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "is_affected_by_fur_coat": false,
            "max_hp": 65,
            "max_hp_gained": 1,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FUZZY_WURM_CRAWLER_WEAK",
            "monster_ids": [
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ANGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.POMMEL_STRIKE"
              }
            ],
            "current_gold": 185,
            "current_hp": 71,
            "damage_taken": 13,
            "gold_gained": 45,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 7,
            "is_affected_by_fur_coat": false,
            "max_hp": 77,
            "max_hp_gained": 1,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.DISTILLED_CHAOS",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.SWIFT_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.RUINED_HELMET",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SEVEN_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 200,
            "current_hp": 49,
            "damage_taken": 6,
            "gold_gained": 44,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "is_affected_by_fur_coat": false,
            "max_hp": 65,
            "max_hp_gained": 1,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.GAME_PIECE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHROG_PARASITE_ELITE",
            "monster_ids": [
              "MONSTER.PHROG_PARASITE",
              "MONSTER.WRIGGLER"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "current_gold": 185,
            "current_hp": 71,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LEGENDS_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "stolen_loot": 0
          },
          {
            "cards_gained": [
              {
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "current_gold": 200,
            "current_hp": 49,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LEGENDS_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 64,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THE_LEGENDS_WERE_TRUE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 185,
            "current_hp": 71,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.UPPERCUT"
            ]
          },
          {
            "current_gold": 200,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 63,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.GLOW"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.MONARCHS_GAZE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.STOKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.IMPERVIOUS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MONARCHS_GAZE"
              }
            ],
            "current_gold": 285,
            "current_hp": 72,
            "damage_taken": 16,
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 17,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 1,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "potion_used": [
              "POTION.STRENGTH_POTION"
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.BEAT_INTO_SHAPE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FOREGONE_CONCLUSION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ONE_FOR_ALL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BEAT_INTO_SHAPE"
              }
            ],
            "current_gold": 300,
            "current_hp": 32,
            "damage_taken": 18,
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "is_affected_by_fur_coat": false,
            "max_hp": 63,
            "max_hp_gained": 1,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.RADIANT_TINCTURE"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.VANTOM_BOSS",
            "monster_ids": [
              "MONSTER.VANTOM"
            ],
            "room_type": "boss",
            "turns_taken": 5
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "GLASS_EYE",
                "title": {
                  "key": "GLASS_EYE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "RADIANT_PEARL",
                "title": {
                  "key": "RADIANT_PEARL.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "TOUCH_OF_OROBAS",
                "title": {
                  "key": "TOUCH_OF_OROBAS.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 285,
            "current_hp": 74,
            "damage_taken": 1,
            "event_choices": [
              {
                "title": {
                  "key": "TOUCH_OF_OROBAS.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 3,
            "is_affected_by_fur_coat": false,
            "max_hp": 74,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.TOUCH_OF_OROBAS",
                "was_picked": true
              },
              {
                "choice": "RELIC.BLACK_BLOOD",
                "was_picked": true
              }
            ],
            "relics_removed": [
              "RELIC.BURNING_BLOOD"
            ],
            "stolen_loot": 0
          },
          {
            "ancient_choice": [
              {
                "TextKey": "SAND_CASTLE",
                "title": {
                  "key": "SAND_CASTLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "DRIFTWOOD",
                "title": {
                  "key": "DRIFTWOOD.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "TOUCH_OF_OROBAS",
                "title": {
                  "key": "TOUCH_OF_OROBAS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 300,
            "current_hp": 62,
            "damage_taken": 1,
            "event_choices": [
              {
                "title": {
                  "key": "DRIFTWOOD.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 31,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.DRIFTWOOD",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.OROBAS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 18,
                  "id": "CARD.HEGEMONY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SHINING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.GLOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STONE_ARMOR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HEGEMONY"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STONE_ARMOR"
              }
            ],
            "current_gold": 305,
            "current_hp": 74,
            "damage_taken": 10,
            "gold_gained": 20,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 10,
            "is_affected_by_fur_coat": false,
            "max_hp": 74,
            "max_hp_gained": 1,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.FAIRY_IN_A_BOTTLE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.LIGHTNING_ROD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BALL_LIGHTNING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 18,
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFRACT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 1,
                "id": "CARD.OVERCLOCK"
              },
              {
                "id": "CARD.HIDDEN_CACHE"
              }
            ],
            "cards_removed": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 1,
                "id": "CARD.OVERCLOCK"
              }
            ],
            "current_gold": 311,
            "current_hp": 51,
            "damage_taken": 12,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 1,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEGEMONY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PALE_BLUE_DOT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ULTIMATE_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ROLLING_BOULDER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "enchantment": {
                  "amount": 1,
                  "id": "ENCHANTMENT.SOWN"
                },
                "floor_added_to_deck": 1,
                "id": "CARD.DEMON_FORM"
              }
            ],
            "current_gold": 63,
            "current_hp": 73,
            "damage_taken": 1,
            "gold_gained": 0,
            "gold_lost": 242,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 73,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.STABLE_SERUM",
                "was_picked": false
              },
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              }
            ],
            "potion_discarded": [
              "POTION.WEAK_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.DOLLYS_MIRROR",
                "was_picked": true
              },
              {
                "choice": "RELIC.WHETSTONE",
                "was_picked": false
              },
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": false
              },
              {
                "choice": "RELIC.DOLLYS_MIRROR",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          },
          {
            "bought_relics": [
              "RELIC.BAG_OF_PREPARATION"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.CRUSH_UNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUNK_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FUSION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ALIGNMENT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PRODUCTION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SALVO"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FERAL"
              }
            ],
            "current_gold": 35,
            "current_hp": 51,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 276,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 61,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.GIGANTIFICATION_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": true
              },
              {
                "choice": "RELIC.VAJRA",
                "was_picked": false
              },
              {
                "choice": "RELIC.CHEMICAL_X",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.SHARP"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.THRASH"
                },
                "enchantment": "ENCHANTMENT.SHARP"
              }
            ],
            "current_gold": 63,
            "current_hp": 72,
            "damage_taken": 1,
            "event_choices": [
              {
                "title": {
                  "key": "SELF_HELP_BOOK.pages.INITIAL.options.READ_THE_BACK.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 72,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "stolen_loot": 0
          },
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.SHARP"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.FLAK_CANNON"
                },
                "enchantment": "ENCHANTMENT.SHARP"
              }
            ],
            "current_gold": 35,
            "current_hp": 51,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SELF_HELP_BOOK.pages.INITIAL.options.READ_THE_BACK.title",
                  "table": "events"
                },
                "variables": {
                  "Enchantment1": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Sharp"
                  },
                  "Enchantment2": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Nimble"
                  },
                  "Enchantment3": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Swift"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 60,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SELF_HELP_BOOK",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.DECAY"
              }
            ],
            "current_gold": 63,
            "current_hp": 71,
            "damage_taken": 1,
            "event_choices": [
              {
                "title": {
                  "key": "LOST_WISP.pages.INITIAL.options.CLAIM.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 71,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.LOST_WISP",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "cards_gained": [
              {
                "id": "CARD.DECAY"
              }
            ],
            "current_gold": 35,
            "current_hp": 51,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LOST_WISP.pages.INITIAL.options.CLAIM.title",
                  "table": "events"
                },
                "variables": {
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Lost Wisp"
                  },
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Decay"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 59,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.LOST_WISP",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.LOST_WISP",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLITTERSTREAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BULWARK"
                },
                "was_picked": false
              }
            ],
            "current_gold": 78,
            "current_hp": 71,
            "damage_taken": 9,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 9,
            "is_affected_by_fur_coat": false,
            "max_hp": 71,
            "max_hp_gained": 1,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.WHITE_NOISE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 22,
                  "id": "CARD.LARGESSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.LUNAR_BLAST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LARGESSE"
              }
            ],
            "current_gold": 47,
            "current_hp": 48,
            "damage_taken": 4,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "is_affected_by_fur_coat": false,
            "max_hp": 59,
            "max_hp_gained": 1,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "potion_used": [
              "POTION.DUPLICATOR"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_EGG"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.BODY_SLAM"
              }
            ],
            "current_gold": 78,
            "current_hp": 28,
            "damage_taken": 43,
            "event_choices": [
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.HOLD_ON_0.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_0.options.HOLD_ON_1.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_1.options.HOLD_ON_2.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_2.options.HOLD_ON_3.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_3.options.HOLD_ON_4.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_4.options.HOLD_ON_5.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_5.options.HOLD_ON_6.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "stolen_loot": 0
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.REBOOT"
              }
            ],
            "current_gold": 47,
            "current_hp": 48,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Reboot"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 58,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SLIPPERY_BRIDGE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "completed_quests": [
              "CARD.SPOILS_MAP"
            ],
            "current_gold": 725,
            "current_hp": 28,
            "damage_taken": 0,
            "gold_gained": 647,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 69,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.BOWLER_HAT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "completed_quests": [
              "CARD.SPOILS_MAP"
            ],
            "current_gold": 690,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 643,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.CAPTAINS_WHEEL",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 25,
                  "id": "CARD.FURNACE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UNRELENTING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FURNACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PANACHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MAYHEM"
                },
                "was_picked": false
              }
            ],
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 3,
                    "id": "ENCHANTMENT.ADROIT"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.FLAME_BARRIER"
                },
                "enchantment": "ENCHANTMENT.ADROIT"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 3,
                    "id": "ENCHANTMENT.ADROIT"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.BLOOD_WALL"
                },
                "enchantment": "ENCHANTMENT.ADROIT"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 3,
                    "id": "ENCHANTMENT.ADROIT"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.DRUM_OF_BATTLE"
                },
                "enchantment": "ENCHANTMENT.ADROIT"
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 25,
                "id": "CARD.FURNACE"
              }
            ],
            "current_gold": 461,
            "current_hp": 28,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 264,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.REGEN_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.KIFUDA",
                "was_picked": true
              },
              {
                "choice": "RELIC.ORICHALCUM",
                "was_picked": false
              },
              {
                "choice": "RELIC.BOOK_OF_FIVE_RINGS",
                "was_picked": false
              },
              {
                "choice": "RELIC.KIFUDA",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          },
          {
            "bought_relics": [
              "RELIC.INTIMIDATING_HELMET",
              "RELIC.RINGING_TRIANGLE",
              "RELIC.POTION_BELT"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.UPROAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GO_FOR_THE_EYES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLASSWORK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TRASH_TO_TREASURE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COORDINATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RALLY"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 21,
                "id": "CARD.DECAY"
              }
            ],
            "current_gold": 5,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 685,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 56,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.POWDERED_DEMISE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.INTIMIDATING_HELMET",
                "was_picked": true
              },
              {
                "choice": "RELIC.RINGING_TRIANGLE",
                "was_picked": true
              },
              {
                "choice": "RELIC.POTION_BELT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 461,
            "current_hp": 28,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 67,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.OFFERING"
            ]
          },
          {
            "current_gold": 5,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 55,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.FERAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.METAMORPHOSIS"
              }
            ],
            "current_gold": 461,
            "current_hp": 53,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SPIRIT_GRAFTER.pages.INITIAL.options.LET_IT_IN.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 25,
            "is_affected_by_fur_coat": false,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "stolen_loot": 0
          },
          {
            "cards_gained": [
              {
                "id": "CARD.METAMORPHOSIS"
              }
            ],
            "current_gold": 5,
            "current_hp": 54,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SPIRIT_GRAFTER.pages.INITIAL.options.LET_IT_IN.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 54,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SPIRIT_GRAFTER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 512,
            "current_hp": 48,
            "damage_taken": 30,
            "gold_gained": 51,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 25,
            "is_affected_by_fur_coat": false,
            "max_hp": 66,
            "max_hp_gained": 1,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "potion_used": [
              "POTION.DISTILLED_CHAOS",
              "POTION.ENERGY_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.POTION_BELT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SPOILS_OF_BATTLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFLECT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SUPERMASSIVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 28,
                  "id": "CARD.CHARGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RAINBOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEGONE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.CHARGE"
              }
            ],
            "current_gold": 43,
            "current_hp": 47,
            "damage_taken": 8,
            "gold_gained": 38,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "is_affected_by_fur_coat": false,
            "max_hp": 54,
            "max_hp_gained": 1,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "potion_choices": [
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STRIKE_DUMMY",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 565,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 53,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "relic_choices": [
              {
                "choice": "RELIC.WAR_PAINT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.BRAND",
              "CARD.IMPERVIOUS"
            ]
          },
          {
            "current_gold": 88,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 45,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 53,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "relic_choices": [
              {
                "choice": "RELIC.GORGET",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 565,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 64,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.HEGEMONY"
            ]
          },
          {
            "current_gold": 88,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 52,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.BEAT_INTO_SHAPE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 565,
            "current_hp": 0,
            "damage_taken": 78,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 30,
            "is_affected_by_fur_coat": false,
            "max_hp": 63,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198038467720,
            "potion_used": [
              "POTION.FAIRY_IN_A_BOTTLE"
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 88,
            "current_hp": 0,
            "damage_taken": 47,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 51,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198930034127,
            "potion_used": [
              "POTION.FLEX_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KNOWLEDGE_DEMON_BOSS",
            "monster_ids": [
              "MONSTER.KNOWLEDGE_DEMON"
            ],
            "room_type": "boss",
            "turns_taken": 8
          }
        ]
      }
    ]
  ],
  "modifiers": [
    {
      "id": "MODIFIER.INSANITY"
    },
    {
      "id": "MODIFIER.CHARACTER_CARDS",
      "props": {
        "model_ids": [
          {
            "name": "CharacterModel",
            "value": "CHARACTER.REGENT"
          }
        ]
      }
    },
    {
      "id": "MODIFIER.TERMINAL"
    }
  ],
  "platform_type": "steam",
  "players": [
    {
      "badges": [
        {
          "id": "ELITE",
          "rarity": "bronze"
        }
      ],
      "character": "CHARACTER.IRONCLAD",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PILLAGE"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.SHARP"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.THRASH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DISMANTLE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ONE_TWO_PUNCH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FEEL_NO_PAIN"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.NOT_YET"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.BRAND"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.SOWN"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.DEMON_FORM"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SECOND_WIND"
        },
        {
          "enchantment": {
            "amount": 3,
            "id": "ENCHANTMENT.ADROIT"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.DRUM_OF_BATTLE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DARK_EMBRACE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.HOWL_FROM_BEYOND"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BRAND"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.HEMOKINESIS"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PERFECTED_STRIKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.HOWL_FROM_BEYOND"
        },
        {
          "enchantment": {
            "amount": 3,
            "id": "ENCHANTMENT.ADROIT"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.FLAME_BARRIER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.IMPERVIOUS"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STOMP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.CRIMSON_MANTLE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.OFFERING"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.INFLAME"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DISMANTLE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FORGOTTEN_RITUAL"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.NOT_YET"
        },
        {
          "enchantment": {
            "amount": 3,
            "id": "ENCHANTMENT.ADROIT"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.BLOOD_WALL"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.NOT_YET"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.RAMPAGE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 12,
          "id": "CARD.UPPERCUT"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.POMMEL_STRIKE"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.MONARCHS_GAZE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.HEGEMONY"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.SOWN"
          },
          "floor_added_to_deck": 19,
          "id": "CARD.DEMON_FORM"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.DECAY"
        },
        {
          "floor_added_to_deck": 25,
          "id": "CARD.FURNACE"
        },
        {
          "floor_added_to_deck": 27,
          "id": "CARD.METAMORPHOSIS"
        }
      ],
      "id": 76561198038467720,
      "max_potion_slot_count": 5,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.BLACK_BLOOD"
        },
        {
          "floor_added_to_deck": 5,
          "id": "RELIC.CHOSEN_CHEESE"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.STRAWBERRY"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.BLOOD_VIAL"
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.RUINED_HELMET"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.TOUCH_OF_OROBAS",
          "props": {
            "model_ids": [
              {
                "name": "StarterRelic",
                "value": "RELIC.BURNING_BLOOD"
              },
              {
                "name": "UpgradedRelic",
                "value": "RELIC.BLACK_BLOOD"
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 19,
          "id": "RELIC.DOLLYS_MIRROR"
        },
        {
          "floor_added_to_deck": 21,
          "id": "RELIC.LOST_WISP"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.BOWLER_HAT"
        },
        {
          "floor_added_to_deck": 25,
          "id": "RELIC.KIFUDA"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.POTION_BELT"
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.WAR_PAINT"
        }
      ]
    },
    {
      "badges": [
        {
          "id": "DAMAGE_LEADER",
          "rarity": "bronze"
        },
        {
          "id": "DEBUFFER",
          "rarity": "bronze"
        },
        {
          "id": "ELITE",
          "rarity": "bronze"
        },
        {
          "id": "KACHING",
          "rarity": "bronze"
        }
      ],
      "character": "CHARACTER.DEFECT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ALL_FOR_ONE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.GO_FOR_THE_EYES"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.REBOOT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.COMPACT"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.SHARP"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.FLAK_CANNON"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ITERATION"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.REBOOT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.CLAW"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.SOWN"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.GENETIC_ALGORITHM",
          "props": {
            "ints": [
              {
                "name": "CurrentBlock",
                "value": 35
              },
              {
                "name": "IncreasedBlock",
                "value": 34
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STORM"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.RAINBOW"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SPINNER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.HELIX_DRILL"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.CONSUMING_SHADOW"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SUNDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FOCUSED_STRIKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.VOLTAIC"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TRASH_TO_TREASURE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.VOLTAIC"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.VOLTAIC"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.OVERCLOCK"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.LEAP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.GO_FOR_THE_EYES"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.MACHINE_LEARNING"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ADAPTIVE_STRIKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FOCUSED_STRIKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ICE_LANCE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.CHILL"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.BLACK_HOLE"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.FUSION"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 11,
          "id": "CARD.GLOW"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 16,
          "id": "CARD.BEAT_INTO_SHAPE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.OVERCLOCK"
        },
        {
          "floor_added_to_deck": 18,
          "id": "CARD.HIDDEN_CACHE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 19,
          "id": "CARD.FERAL"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.LARGESSE"
        },
        {
          "floor_added_to_deck": 27,
          "id": "CARD.METAMORPHOSIS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 28,
          "id": "CARD.CHARGE"
        }
      ],
      "id": 76561198930034127,
      "max_potion_slot_count": 5,
      "potions": [
        {
          "id": "POTION.VULNERABLE_POTION",
          "slot_index": 0
        },
        {
          "id": "POTION.FIRE_POTION",
          "slot_index": 1
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.CRACKED_CORE"
        },
        {
          "floor_added_to_deck": 5,
          "id": "RELIC.CHOSEN_CHEESE"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.RAZOR_TOOTH"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.JUZU_BRACELET"
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.GAME_PIECE"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.DRIFTWOOD"
        },
        {
          "floor_added_to_deck": 19,
          "id": "RELIC.BAG_OF_PREPARATION"
        },
        {
          "floor_added_to_deck": 21,
          "id": "RELIC.LOST_WISP"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.CAPTAINS_WHEEL"
        },
        {
          "floor_added_to_deck": 25,
          "id": "RELIC.INTIMIDATING_HELMET"
        },
        {
          "floor_added_to_deck": 25,
          "id": "RELIC.RINGING_TRIANGLE"
        },
        {
          "floor_added_to_deck": 25,
          "id": "RELIC.POTION_BELT"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.STRIKE_DUMMY"
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.GORGET"
        }
      ]
    }
  ],
  "run_time": 1847,
  "schema_version": 9,
  "seed": "14_07_2026_2P",
  "start_time": 1784059907,
  "was_abandoned": false,
  "win": false
}